### ISSUE TITLE
偶现Crash现象

### ISSUE THREAD

**Issue by Wmmeng** [Qihoo360/DroidPlugin#106]
在使用过程中偶现此crash bug：
java.util.ConcurrentModificationException
                                                                            at java.util.HashMap$HashIterator.nextEntry(HashMap.java:792)
                                                                            at java.util.HashMap$ValueIterator.next(HashMap.java:824)
                                                                            at com.morgoo.droidplugin.am.RunningProcesList.isPersistentApplication(RunningProcesList.java:97)
                                                                            at com.morgoo.droidplugin.am.MyActivityManagerService.runProcessGC(MyActivityManagerService.java:413)
                                                                            at com.morgoo.droidplugin.am.MyActivityManagerService.selectStubActivityInfo(MyActivityManagerService.java:277)
                                                                            at com.morgoo.droidplugin.pm.IPluginManagerImpl.selectStubActivityInfo(IPluginManagerImpl.java:1204)
                                                                            at com.morgoo.droidplugin.pm.IPluginManagerImpl.selectStubActivityInfoByIntent(IPluginManagerImpl.java:1220)
                                                                            at com.morgoo.droidplugin.pm.IPluginManager$Stub.onTransact(IPluginManager.java:532)
                                                                            at android.os.Binder.execTransact(Binder.java:351)
                                                                            at dalvik.system.NativeStart.run(Native Method)

**Comment by cmzy** [comment]
bug，但是暂时先不修改。
