### ISSUE TITLE
java.lang.OutOfMemoryError: Could not allocate JNI Env

### ISSUE THREAD

**Issue by cundong** [Qihoo360/DroidPlugin#120]
Nexus5，手机助手经常性崩溃。

01-18 16:50:21.855 27852-27852/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.qihoo.appstore:PluginP08, PID: 27852
                                                   java.lang.OutOfMemoryError: Could not allocate JNI Env
                                                       at java.lang.Thread.nativeCreate(Native Method)
                                                       at java.lang.Thread.start(Thread.java:1063)
                                                       at com.morgoo.droidplugin.stub.AbstractServiceStub.a(Unknown Source)
                                                       at com.morgoo.droidplugin.stub.AbstractServiceStub.onStart(Unknown Source)
                                                       at android.app.Service.onStartCommand(Service.java:459)
                                                       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3010)
                                                       at android.app.ActivityThread.-wrap17(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1442)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by qdrzwd** [comment]
这个问题我也遇到了，从dump出的hprof文件来看，Java层占用的内存并不高，线程数也不多。不知道为什么会有这个异常。
