### ISSUE TITLE
个别手机安装后进入不了  红米    报错如下

### ISSUE THREAD

**Issue by xuliang271699** [Qihoo360/DroidPlugin#126]
FATAL EXCEPTION: main
                                                                                 Process: com.careerforce.mianshi:PluginP02, PID: 4015
                                                                                 java.lang.SecurityException: Invalid mkdirs path: /storage/sdcard1/Android/data/com.careerforce.mianshi.shangji_ms_main/cache/
                                                                                     at android.os.Parcel.readException(Parcel.java:1465)
                                                                                     at android.os.Parcel.readException(Parcel.java:1419)
                                                                                     at android.os.storage.IMountService$Stub$Proxy.mkdirs(IMountService.java:750)
                                                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                     at com.morgoo.droidplugin.hook.HookedMethodHandler.doHookInner(HookedMethodHandler.java:52)
                                                                                     at com.morgoo.droidplugin.hook.binder.BinderHook.invoke(BinderHook.java:57)
                                                                                     at com.morgoo.droidplugin.hook.binder.IMountServiceBinder.invoke(IMountServiceBinder.java:35)
                                                                                     at $Proxy5.mkdirs(Native Method)
                                                                                     at android.app.ContextImpl.ensureDirsExistOrFilter(ContextImpl.java:2301)
                                                                                     at android.app.ContextImpl.getExternalCacheDirs(ContextImpl.java:1050)
                                                                                     at android.app.ContextImpl.getExternalCacheDir(ContextImpl.java:1039)
                                                                                     at android.content.ContextWrapper.getExternalCacheDir(ContextWrapper.java:235)
                                                                                     at in.srain.cube.cache.DiskFileUtils.getExternalCacheDir(DiskFileUtils.java:136)
                                                                                     at in.srain.cube.cache.DiskFileUtils.getDiskCacheDir(DiskFileUtils.java:80)
                                                                                     at in.srain.cube.cache.DiskFileUtils.getDiskCacheDir(DiskFileUtils.java:55)
                                                                                     at in.srain.cube.image.ImageLoaderFactory.getImageFileProvider(ImageLoaderFactory.java:118)
                                                                                     at in.srain.cube.image.ImageLoaderFactory.getDefaultImageProvider(ImageLoaderFactory.java:205)
                                                                                     at in.srain.cube.image.ImageLoaderFactory.create(ImageLoaderFactory.java:137)
                                                                                     at com.careerforce.mianshi.shangji_ms_main.Adapter.SquareResumeListAdapter.<init>(SquareResumeListAdapter.java:32)
                                                                                     at com.careerforce.mianshi.shangji_ms_main.Fragment.SquareFragment.onCreateView(SquareFragment.java:120)
                                                                                     at android.support.v4.app.Fragment.performCreateView(Fragment.java:1789)
                                                                                     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:955)
                                                                                     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
                                                                                     at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:740)
                                                                                     at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1501)
                                                                                     at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:490)
                                                                                     at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:163)
                                                                                     at android.support.v4.view.ViewPager.populate(ViewPager.java:1105)
                                                                                     at android.support.v4.view.ViewPager.populate(ViewPager.java:951)
                                                                                     at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1473)
                                                                                     at android.view.View.measure(View.java:16854)
                                                                                     at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:824)
                                                                                     at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:500)
                                                                                     at android.view.View.measure(View.java:16854)
                                                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5421)
                                                                                     at android.widget.FrameLayout.onMeasure(FrameLayout.java:340)
                                                                                     at android.view.View.measure(View.java:16854)

**Comment by cmzy** [comment]
这是用的哪个版本的droidplugin?貌似我已经解决了啊

**Comment by zgzczzw** [comment]
IMountServiceHookHandle.java 的 
final boolean isAndroiDataHostPath = path.indexOf(ANDROID_DATA) < 0;
 final boolean isAndroiObbHostPath = path.indexOf(ANDROID_OBB) < 0;

这里有问题，导致无法替换mkdir的路径名，有的手机权限管理严格，就会有问题。都改成>=即可，用contains也可以
