### ISSUE TITLE
锤子手机T1，使用DroidPlugin后，所有引用webview的地方都会导致app Crash。

### ISSUE THREAD

**Issue by DavidYes** [Qihoo360/DroidPlugin#137]
日志03-02 14:12:19.361 1026-1026/com.example.TestPlugin:PluginP02 W/System.err: java.lang.ClassCastException: $Proxy18 cannot be cast to com.android.webview.chromium.WebViewChromium
03-02 14:12:19.361 1026-1026/com.example.TestPlugin:PluginP02 W/System.err:     at com.android.webview.chromium.WebViewContentsClientAdapter.onProgressChanged(WebViewContentsClientAdapter.java:271)
03-02 14:12:19.361 1026-1026/com.example.TestPlugin:PluginP02 W/System.err:     at com.android.org.chromium.android_webview.AwWebContentsDelegateAdapter.onLoadProgressChanged(AwWebContentsDelegateAdapter.java:40)
03-02 14:12:19.361 1026-1026/com.example.TestPlugin:PluginP02 W/System.err:     at com.android.org.chromium.components.web_contents_delegate_android.WebContentsDelegateAndroid.notifyLoadProgressChanged(WebContentsDelegateAndroid.java:89)
03-02 14:12:19.361 1026-1026/com.example.TestPlugin:PluginP02 W/System.err:     at com.android.org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
03-02 14:12:19.361 1026-1026/com.example.TestPlugin:PluginP02 W/System.err:     at com.android.org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:27)
03-02 14:12:19.361 1026-1026/com.example.TestPlugin:PluginP02 W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
03-02 14:12:19.361 1026-1026/com.example.TestPlugin:PluginP02 W/System.err:     at android.os.Looper.loop(Looper.java:136)
03-02 14:12:19.361 1026-1026/com.example.TestPlugin:PluginP02 W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5094)
03-02 14:12:19.361 1026-1026/com.example.TestPlugin:PluginP02 W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
03-02 14:12:19.361 1026-1026/com.example.TestPlugin:PluginP02 W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
03-02 14:12:19.361 1026-1026/com.example.TestPlugin:PluginP02 W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
03-02 14:12:19.361 1026-1026/com.example.TestPlugin:PluginP02 W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:702)
03-02 14:12:19.361 1026-1026/com.example.TestPlugin:PluginP02 W/System.err:     at dalvik.system.NativeStart.main(Native Method)

**Comment by jtbuaa** [comment]
T1的确起不来，但T2可以。T1是4.4，T2是5.1

**Comment by jtbuaa** [comment]
不过最近T1又好了，奇怪

**Comment by cmzy** [comment]
我处理过了
