### ISSUE TITLE
BUG Fatal Exception

### ISSUE THREAD

**Issue by luoqii** [Qihoo360/DroidPlugin#140]
03-07 17:05:19.766 15989-16091/com.example.TestPlugin:PluginP02 D/Environment: tfprimary = 0
03-07 17:05:19.806 15989-16091/com.example.TestPlugin:PluginP02 E/AndroidRuntime: FATAL EXCEPTION: Thread-314
                                                                                  Process: com.example.TestPlugin:PluginP02, PID: 15989
                                                                                  java.util.MissingFormatArgumentException: Format specifier: s
                                                                                      at java.util.Formatter.getArgument(Formatter.java:1111)
                                                                                      at java.util.Formatter.doFormat(Formatter.java:1076)
                                                                                      at java.util.Formatter.format(Formatter.java:1042)
                                                                                      at java.util.Formatter.format(Formatter.java:1011)
                                                                                      at java.lang.String.format(String.java:1999)
                                                                                      at java.lang.String.format(String.java:1973)
                                                                                      at com.morgoo.helper.Log.e(Log.java:248)
                                                                                      at com.morgoo.droidplugin.pm.IPluginManagerImpl.loadAllPlugin(IPluginManagerImpl.java:155)
                                                                                      at com.morgoo.droidplugin.pm.IPluginManagerImpl.onCreateInner(IPluginManagerImpl.java:113)
                                                                                      at com.morgoo.droidplugin.pm.IPluginManagerImpl.access$000(IPluginManagerImpl.java:81)
                                                                                      at com.morgoo.droidplugin.pm.IPluginManagerImpl$1.run(IPluginManagerImpl.java:107)

**Comment by cmzy** [comment]
fix on https://github.com/Qihoo360/DroidPlugin/commit/c2b7f9d6599b407f3645df1f072829f386d48f14
