### ISSUE TITLE
如果plugin 中有包含native 调用， 在loadLibrary的时候报错

### ISSUE THREAD

**Issue by SheepYoung** [Qihoo360/DroidPlugin#152]
Process: com.example.TestPlugin:PluginP02, PID: 31480
                                                                                  java.lang.UnsatisfiedLinkError: Couldn't load jingle_peerconnection_so from loader com.morgoo.droidplugin.core.PluginClassLoader[DexPathList[[zip file "/data/data/com.example.TestPlugin/Plugin/com.*****i/apk/base-1.apk"],nativeLibraryDirectories=[/data/data/com.example.TestPlugin/Plugin/com.******/lib, /vendor/lib, /system/lib]]]: findLibrary returned null
                                                                                      at java.lang.Runtime.loadLibrary(Runtime.java:358)
                                                                                      at java.lang.System.loadLibrary(System.java:555)
......
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                      at android.os.Looper.loop(Looper.java:136)
                                                                                      at org.appspot.apprtc.util.LooperExecutor.run(LooperExecutor.java:40)

**Comment by SheepYoung** [comment]
update

**Comment by KenshinTang** [comment]
碰到了同样的问题,求解.

**Comment by SheepYoung** [comment]
昨天试了，直接讲动态库解压到对应的目录即可运行…
在2016年03月25日 08:33，KenshinTang 写道:

碰到了同样的问题,求解.

**Comment by KenshinTang** [comment]
对应的目录不是/data/data吗?  有权限?

**Comment by singlersu** [comment]
这个问题我也遇到了，经过分析发现，在findSoPath()函数中使用了Arrays.binarySearch(BuildCompat.SUPPORTED_64_BIT_ABIS, abi) ，二分查找字符串应该是不行的，二分查找字符串那部分自己写个函数替换就好了，页希望做着能修改一下这个地方

**Comment by singlersu** [comment]
@cmzy

**Comment by SheepYoung** [comment]
多谢，我已经解决，我的方案是在插件安装的时候多做一步，讲将so解压到插件目录的对应目录上，问题解决


在 2016年3月25日，21:12，singlersu <notifications@github.com<mailto:notifications@github.com>> 写道：


这个问题我也遇到了，经过分析发现，在findSoPath()函数中使用了Arrays.binarySearch(BuildCompat.SUPPORTED_64_BIT_ABIS, abi) ，二分查找字符串应该是不行的，二分查找字符串那部分自己写个函数替换就好了，页希望做着能修改一下这个地方

―

**Comment by cmzy** [comment]
fixed on https://github.com/Qihoo360/DroidPlugin/commit/c379a4ea0ca1bdc06105d7a3cf1341787c675269

因为二分查找之前没排序。that is not cool!
