### ISSUE TITLE
测试apk启动时报错，自定义的Application

### ISSUE THREAD

**Issue by testcc3** [Qihoo360/DroidPlugin#154]
03-27 22:47:51.975: I/Process(9466): Sending signal. PID: 9466 SIG: 9
03-27 22:48:03.088: I/dalvikvm(9597): Could not find method com.morgoo.droidplugin.PluginHelper.getInstance, referenced from method com.test.hulu.activity.MyApplication.attachBaseContext
03-27 22:48:03.088: W/dalvikvm(9597): VFY: unable to resolve static method 5717: Lcom/morgoo/droidplugin/PluginHelper;.getInstance ()Lcom/morgoo/droidplugin/PluginHelper;
03-27 22:48:03.089: D/dalvikvm(9597): VFY: replacing opcode 0x71 at 0x0000
03-27 22:48:03.089: I/dalvikvm(9597): Could not find method com.morgoo.droidplugin.PluginHelper.getInstance, referenced from method com.test.hulu.activity.MyApplication.onCreate
03-27 22:48:03.089: W/dalvikvm(9597): VFY: unable to resolve static method 5717: Lcom/morgoo/droidplugin/PluginHelper;.getInstance ()Lcom/morgoo/droidplugin/PluginHelper;
03-27 22:48:03.089: D/dalvikvm(9597): VFY: replacing opcode 0x71 at 0x0003
03-27 22:48:03.089: D/AndroidRuntime(9597): Shutting down VM
03-27 22:48:03.089: W/dalvikvm(9597): threadid=1: thread exiting with uncaught exception (group=0x41706ba8)
03-27 22:48:03.091: E/AndroidRuntime(9597): FATAL EXCEPTION: main
03-27 22:48:03.091: E/AndroidRuntime(9597): Process: com.test.hulu, PID: 9597
03-27 22:48:03.091: E/AndroidRuntime(9597): java.lang.NoClassDefFoundError: com.morgoo.droidplugin.PluginHelper
03-27 22:48:03.091: E/AndroidRuntime(9597): 	at com.test.hulu.activity.MyApplication.attachBaseContext(MyApplication.java:31)
03-27 22:48:03.091: E/AndroidRuntime(9597): 	at android.app.Application.attach(Application.java:185)
03-27 22:48:03.091: E/AndroidRuntime(9597): 	at android.app.Instrumentation.newApplication(Instrumentation.java:991)
03-27 22:48:03.091: E/AndroidRuntime(9597): 	at android.app.Instrumentation.newApplication(Instrumentation.java:975)
03-27 22:48:03.091: E/AndroidRuntime(9597): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:504)
03-27 22:48:03.091: E/AndroidRuntime(9597): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4314)
03-27 22:48:03.091: E/AndroidRuntime(9597): 	at android.app.ActivityThread.access$1500(ActivityThread.java:138)
03-27 22:48:03.091: E/AndroidRuntime(9597): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1261)
03-27 22:48:03.091: E/AndroidRuntime(9597): 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-27 22:48:03.091: E/AndroidRuntime(9597): 	at android.os.Looper.loop(Looper.java:136)
03-27 22:48:03.091: E/AndroidRuntime(9597): 	at android.app.ActivityThread.main(ActivityThread.java:5016)
03-27 22:48:03.091: E/AndroidRuntime(9597): 	at java.lang.reflect.Method.invokeNative(Native Method)
03-27 22:48:03.091: E/AndroidRuntime(9597): 	at java.lang.reflect.Method.invoke(Method.java:515)
03-27 22:48:03.091: E/AndroidRuntime(9597): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
03-27 22:48:03.091: E/AndroidRuntime(9597): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608)
03-27 22:48:03.091: E/AndroidRuntime(9597): 	at dalvik.system.NativeStart.main(Native Method)

public class MyApplication extends Application
{

   private WindowManager.LayoutParams wmParams = new WindowManager.LayoutParams();

    public WindowManager.LayoutParams getMywmParams()
    {
        return wmParams;
    }
    
    @Override
    public void onCreate() {
        super.onCreate();
        //这里必须在super.onCreate方法之后，顺序不能变
        PluginHelper.getInstance().applicationOnCreate(getBaseContext());
    }
     
    @Override
    protected void attachBaseContext(Context base) {
        PluginHelper.getInstance().applicationAttachBaseContext(base);
    }
    
}

**Comment by testcc3** [comment]
添加本地lib已解决
