### ISSUE TITLE
启动插件APK的时候经常提示努力加载中，然后一直加载不出来

### ISSUE THREAD

**Issue by LLbgithub** [Qihoo360/DroidPlugin#26]

**Comment by tjianli** [comment]
也碰到这种问题，在小米4，系统4.4.4
测试apk，http://pan.baidu.com/s/1eQ99Jmq

**Comment by tjianli** [comment]
也碰到这种问题，在小米4，系统4.4.4
测试apk,http://www.pgyer.com/VCVx

**Comment by tjianli** [comment]
log文件是这样的:

2015-09-25 00:37:28.702 4261-10233/? E/PluginHelper getMainLooper MessageQueue.IdleHandler:{ when=-42ms what=100 obj=ActivityRecord{42d62ec0 token=android.os.BinderProxy@42d62678 {com.example.TestPlugin/com.example.TestPlugin.MyActivity}} target=android.app.ActivityThread$H }
2015-09-25 00:37:28.733 4261-10233/? W/IWindowManagerBinderHook onInstall writeStaticField to sWindowManager fail
java.lang.ClassNotFoundException: com.android.internal.policy.PhoneWindow$WindowManagerHolder
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:251)
	at java.lang.Class.forName(Class.java:216)
	at com.morgoo.droidplugin.hook.binder.IWindowManagerBinderHook.onInstall(IWindowManagerBinderHook.java:72)
	at com.morgoo.droidplugin.hook.HookFactory.installHook(HookFactory.java:104)
	at com.morgoo.droidplugin.hook.HookFactory.installHook(HookFactory.java:123)
	at com.morgoo.droidplugin.core.PluginProcessManager.installHook(PluginProcessManager.java:297)
	at com.morgoo.droidplugin.PluginHelper.initPlugin(PluginHelper.java:76)
	at com.morgoo.droidplugin.PluginHelper.applicationOnCreate(PluginHelper.java:63)
	at com.morgoo.droidplugin.PluginApplication.onCreate(PluginApplication.java:45)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4374)
	at android.app.ActivityThread.access$1500(ActivityThread.java:141)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1264)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5049)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NoClassDefFoundError: com/android/internal/policy/PhoneWindow$WindowManagerHolder
	... 22 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.internal.policy.PhoneWindow$WindowManagerHolder" on path: DexPathList[[zip file "/data/app/com.example.TestPlugin-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.example.TestPlugin-1, /vendor/lib, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
	... 22 more

2015-09-25 00:37:28.770 4261-10233/? I/IActivityManagerHook Install ActivityManager Hook 2 old=android.app.ActivityManagerProxy@42d61088,new=android.app.ActivityManagerProxy@42d61088
2015-09-25 00:37:28.771 4261-10233/? E/IActivityManagerHook Install ActivityManager 3 Hook  old=android.app.ActivityManagerProxy@42d61088,new=android.app.ActivityManagerProxy@42d61088
2015-09-25 00:37:28.773 4261-10233/? I/PluginCallbackHook PluginCallbackHook has installed
2015-09-25 00:37:28.774 4261-10233/? I/InstrumentationHook Install Instrumentation Hook old=android.app.Instrumentation android.app.ActivityThread.mInstrumentation,new=com.morgoo.droidplugin.hook.handle.PluginInstrumentation@42e2c420
2015-09-25 00:37:28.820 4261-10233/? I/PluginHelper Init plugin in process cost 122 ms
2015-09-25 00:37:28.822 4261-10233/? I/PluginCallback handleMessage(100,LAUNCH_ACTIVITY) cost 0 ms
2015-09-25 00:37:28.830 4261-10233/? W/IWindowManagerBinderHook fixWindowManagerHook writeStaticField to sWindowManager fail
java.lang.ClassNotFoundException: com.android.internal.policy.impl.MiuiPhoneWindow$WindowManagerHolder
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:251)
	at java.lang.Class.forName(Class.java:216)
	at com.morgoo.droidplugin.hook.binder.IWindowManagerBinderHook.fixWindowManagerHook(IWindowManagerBinderHook.java:83)
	at com.morgoo.droidplugin.hook.handle.PluginInstrumentation.callActivityOnCreate(PluginInstrumentation.java:68)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2156)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2241)
	at android.app.ActivityThread.access$800(ActivityThread.java:141)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1204)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5049)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NoClassDefFoundError: com/android/internal/policy/impl/MiuiPhoneWindow$WindowManagerHolder
	... 17 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.internal.policy.impl.MiuiPhoneWindow$WindowManagerHolder" on path: DexPathList[[zip file "/data/app/com.example.TestPlugin-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.example.TestPlugin-1, /vendor/lib, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
	... 17 more

2015-09-25 00:37:28.915 4261-10233/? I/PluginCallback handleMessage(114,CREATE_SERVICE) cost 0 ms
2015-09-25 00:37:28.920 4261-10233/? I/PluginCallback handleMessage(115,SERVICE_ARGS) cost 0 ms
2015-09-25 00:37:28.924 4261-10233/? I/PluginCallback handleMessage(121,BIND_SERVICE) cost 0 ms
2015-09-25 00:37:28.937 4261-10233/? I/IPluginManagerImpl Search apk cost 2 ms
2015-09-25 00:37:29.027 4261-10233/? I/PluginManager onServiceConnected connected OK!
2015-09-25 00:37:29.029 4261-10233/? I/IPluginManagerImpl Read test.testb signature of 0,md5=00E3580658AA42CCDC0BBB66C94C6346
2015-09-25 00:37:29.031 4261-10233/? I/IPluginManagerImpl Parse /data/data/com.example.TestPlugin/Plugin/test.testb/apk/base-1.apk apk cost 102 ms
2015-09-25 00:37:29.036 4261-10233/? I/IPluginManagerImpl Parse all apk cost 102 ms
2015-09-25 00:37:29.079 4261-10233/? I/IPluginManagerImpl ActivityManagerService.onCreate 57 ms
2015-09-25 00:37:29.097 4261-10233/? I/PluginCallbackHook PluginCallbackHook has installed,skip
2015-09-25 00:37:29.104 4261-10233/? I/InstrumentationHook Instrumentation has installed,skip
2015-09-25 00:37:29.106 4261-10233/? I/PluginManager PluginManager ready!
2015-09-25 00:37:29.109 4261-10233/? I/PackageParserApi21 get generatePackageInfo 1 fail
java.lang.NoSuchMethodException: generatePackageInfo [class android.content.pm.PackageParser$Package, class [I, int, long, long, interface java.util.Set, class android.content.pm.PackageUserState, int]
	at java.lang.Class.getConstructorOrMethod(Class.java:472)
	at java.lang.Class.getMethod(Class.java:857)
	at com.morgoo.droidplugin.reflect.MethodUtils.getAccessibleMethod(MethodUtils.java:143)
	at com.morgoo.droidplugin.pm.parser.PackageParserApi21.generatePackageInfo(PackageParserApi21.java:190)
	at com.morgoo.droidplugin.pm.parser.PluginPackageParser.getPackageInfo(PluginPackageParser.java:362)
	at com.morgoo.droidplugin.pm.IPluginManagerImpl.getInstalledPackages(IPluginManagerImpl.java:554)
	at com.morgoo.droidplugin.pm.PluginManager.getInstalledPackages(PluginManager.java:418)
	at com.example.TestPlugin.InstalledFragment$2.run(InstalledFragment.java:90)

2015-09-25 00:37:29.308 4261-10233/? I/PackageParserApi21 get generatePackageInfo 1 fail
java.lang.NoSuchMethodException: generatePackageInfo [class android.content.pm.PackageParser$Package, class [I, int, long, long, interface java.util.Set, class android.content.pm.PackageUserState, int]
	at java.lang.Class.getConstructorOrMethod(Class.java:472)
	at java.lang.Class.getMethod(Class.java:857)
	at com.morgoo.droidplugin.reflect.MethodUtils.getAccessibleMethod(MethodUtils.java:143)
	at com.morgoo.droidplugin.pm.parser.PackageParserApi21.generatePackageInfo(PackageParserApi21.java:190)
	at com.morgoo.droidplugin.pm.parser.PluginPackageParser.getPackageInfo(PluginPackageParser.java:362)
	at com.morgoo.droidplugin.pm.IPluginManagerImpl.getPackageInfo(IPluginManagerImpl.java:257)
	at com.morgoo.droidplugin.pm.PluginManager.getPackageInfo(PluginManager.java:210)
	at com.example.TestPlugin.ApkFragment$1.getView(ApkFragment.java:77)
	at android.widget.AbsListView.obtainView(AbsListView.java:2257)
	at android.widget.ListView.makeAndAddView(ListView.java:1790)
	at android.widget.ListView.fillDown(ListView.java:691)
	at android.widget.ListView.fillFromTop(ListView.java:752)
	at android.widget.ListView.layoutChildren(ListView.java:1616)
	at android.widget.AbsListView.onLayout(AbsListView.java:2089)
	at android.view.View.layout(View.java:14845)
	at android.view.ViewGroup.layout(ViewGroup.java:4631)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
	at android.view.View.layout(View.java:14845)
	at android.view.ViewGroup.layout(ViewGroup.java:4631)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
	at android.view.View.layout(View.java:14845)
	at android.view.ViewGroup.layout(ViewGroup.java:4631)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
	at android.view.View.layout(View.java:14845)
	at android.view.ViewGroup.layout(ViewGroup.java:4631)
	at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1594)
	at android.view.View.layout(View.java:14845)
	at android.view.ViewGroup.layout(ViewGroup.java:4631)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
	at android.view.View.layout(View.java:14845)
	at android.view.ViewGroup.layout(ViewGroup.java:4631)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
	at android.view.View.layout(View.java:14845)
	at android.view.ViewGroup.layout(ViewGroup.java:4631)
	at com.android.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:374)
	at android.view.View.layout(View.java:14845)
	at android.view.ViewGroup.layout(ViewGroup.java:4631)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
	at android.view.View.layout(View.java:14845)
	at android.view.ViewGroup.layout(ViewGroup.java:4631)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2026)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1783)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1039)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5648)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
	at android.view.Choreographer.doCallbacks(Choreographer.java:574)
	at android.view.Choreographer.doFrame(Choreographer.java:544)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5049)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
	at dalvik.system.NativeStart.main(Native Method)

2015-09-25 00:37:31.384 4261-10233/? I/HookedMethodHandler doHookInner method(android.content.pm.IPackageManager.queryIntentActivities) cost 169 ms
2015-09-25 00:37:31.395 4261-10233/? I/HookedMethodHandler doHookInner method(android.app.IActivityManager.getRunningAppProcesses) cost 14 ms
2015-09-25 00:37:31.409 4261-10233/? I/PackageParserApi21 get generatePackageInfo 1 fail
java.lang.NoSuchMethodException: generatePackageInfo [class android.content.pm.PackageParser$Package, class [I, int, long, long, interface java.util.Set, class android.content.pm.PackageUserState, int]
	at java.lang.Class.getConstructorOrMethod(Class.java:472)
	at java.lang.Class.getMethod(Class.java:857)
	at com.morgoo.droidplugin.reflect.MethodUtils.getAccessibleMethod(MethodUtils.java:143)
	at com.morgoo.droidplugin.pm.parser.PackageParserApi21.generatePackageInfo(PackageParserApi21.java:190)
	at com.morgoo.droidplugin.pm.parser.PluginPackageParser.getPackageInfo(PluginPackageParser.java:362)
	at com.morgoo.droidplugin.pm.IPluginManagerImpl.getPackageInfo(IPluginManagerImpl.java:257)
	at com.morgoo.droidplugin.pm.IPluginManagerImpl.getSignature(IPluginManagerImpl.java:1185)
	at com.morgoo.droidplugin.pm.IPluginManagerImpl.checkSignatures(IPluginManagerImpl.java:1147)
	at com.morgoo.droidplugin.pm.PluginManager.checkSignatures(PluginManager.java:951)
	at com.morgoo.droidplugin.am.RunningProcesList.getStubProcessByTarget(RunningProcesList.java:81)
	at com.morgoo.droidplugin.am.MyActivityManagerService.selectStubActivityInfo(MyActivityManagerService.java:308)
	at com.morgoo.droidplugin.pm.IPluginManagerImpl.selectStubActivityInfo(IPluginManagerImpl.java:1204)
	at com.morgoo.droidplugin.pm.IPluginManagerImpl.selectStubActivityInfoByIntent(IPluginManagerImpl.java:1220)
	at com.morgoo.droidplugin.pm.PluginManager.selectStubActivityInfo(PluginManager.java:610)
	at com.morgoo.droidplugin.hook.handle.IActivityManagerHookHandle.selectProxyActivity(IActivityManagerHookHandle.java:1985)
	at com.morgoo.droidplugin.hook.handle.IActivityManagerHookHandle.access$300(IActivityManagerHookHandle.java:66)
	at com.morgoo.droidplugin.hook.handle.IActivityManagerHookHandle$startActivity.doReplaceIntentForStartActivityAPIHigh(IActivityManagerHookHandle.java:153)
	at com.morgoo.droidplugin.hook.handle.IActivityManagerHookHandle$startActivity.beforeInvoke(IActivityManagerHookHandle.java:255)
	at com.morgoo.droidplugin.hook.HookedMethodHandler.doHookInner(HookedMethodHandler.java:48)
	at com.morgoo.droidplugin.hook.proxy.ProxyHook.invoke(ProxyHook.java:61)
	at $Proxy12.startActivity(Native Method)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1419)
	at android.app.Activity.startActivityForResult(Activity.java:3442)
	at android.app.Activity.startActivityForResult(Activity.java:3403)
	at android.support.v4.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:826)
	at android.support.v4.app.Fragment.startActivity(Fragment.java:896)
	at com.example.TestPlugin.InstalledFragment.onListItemClick(InstalledFragment.java:51)
	at com.example.TestPlugin.InstalledFragment$3$1.onClick(InstalledFragment.java:147)
	at android.view.View.performClick(View.java:4444)
	at android.view.View$PerformClick.run(View.java:18457)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5049)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
	at dalvik.system.NativeStart.main(Native Method)

2015-09-25 00:37:31.429 4261-10233/? I/IPackageManagerHookHandle getPackageInfo(com.example.TestPlugin) fail,pkginfo is null
2015-09-25 00:37:31.431 4261-10233/? I/HookedMethodHandler doHookInner method(android.content.pm.IPackageManager.getPackageInfo) cost 7 ms
2015-09-25 00:37:31.449 4261-10233/? I/HookedMethodHandler doHookInner method(android.app.IActivityManager.startActivity) cost 67 ms
2015-09-25 00:37:31.453 4261-10233/? I/PluginCallback handleMessage(101,PAUSE_ACTIVITY) cost 0 ms
2015-09-25 00:37:31.870 4261-10233/? I/PluginCallback handleMessage(115,SERVICE_ARGS) cost 0 ms
2015-09-25 00:37:31.922 4261-10233/? I/HookedMethodHandler doHookInner method(android.app.IActivityManager.getRunningAppProcesses) cost 6 ms
2015-09-25 00:37:32.078 4261-10233/? I/PluginCallback handleMessage(104,STOP_ACTIVITY_HIDE) cost 0 ms
2015-09-25 00:37:34.627 4261-10233/? I/PluginCallback handleMessage(107,RESUME_ACTIVITY) cost 1 ms
2015-09-25 00:37:37.125 4261-10233/? I/PluginCallback handleMessage(101,PAUSE_ACTIVITY) cost 0 ms
2015-09-25 00:37:37.932 4261-10233/? I/PluginCallback handleMessage(104,STOP_ACTIVITY_HIDE) cost 1 ms
2015-09-25 00:37:37.957 4261-10233/? I/PluginCallback handleMessage(140,TRIM_MEMORY) cost 0 ms
2015-09-25 00:37:38.695 4261-10233/? I/PluginCallback handleMessage(132,ENABLE_JIT) cost 0 ms

**Comment by cmzy** [comment]
已经解决了，更新下看看，另外按照文档重新做一遍。我少加了一个地方。

and change PluginManager.STUB_AUTHORITY_NAME to your value:

  PluginManager.STUB_AUTHORITY_NAME="com.example.droidplugin_stub"

**Comment by ckitterl** [comment]
@cmzy 还是会提示这个错误
java.lang.ClassNotFoundException: com.android.internal.policy.PhoneWindow$WindowManagerHolder
应该是sdk版本的问题吧？
