### ISSUE TITLE
关于运行插件的一些问题

### ISSUE THREAD

**Issue by codehz** [Qihoo360/DroidPlugin#3]
看起来是没有处理宿主的启动应用的问题。。。
```
com.example.TestPlugin E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.example.TestPlugin, PID: 9840
    android.content.ActivityNotFoundException: Unable to find explicit activity class {com.android.inputmethod.latin/com.android.inputmethod.latin.setup.SetupActivity}; have you declared this activity in your AndroidManifest.xml?
            at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1777)
            at android.app.Instrumentation.execStartActivity(Instrumentation.java:1501)
            at android.app.Activity.startActivityForResult(Activity.java:3745)
            at android.app.Activity.startActivityForResult(Activity.java:3706)
            at android.support.v4.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:826)
            at android.support.v4.app.Fragment.startActivity(Fragment.java:896)
            at com.example.TestPlugin.InstalledFragment.onListItemClick(InstalledFragment.java:51)
            at com.example.TestPlugin.InstalledFragment$3$1.onClick(InstalledFragment.java:147)
            at android.view.View.performClick(View.java:4781)
            at android.view.View$PerformClick.run(View.java:19873)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
```

**Comment by codehz** [comment]
感觉是Hook.java的mEnable的问题。。。虽然没仔细研究运行细节。。。感觉好像和时序有点关系。。。。导致InstallHook时没有启用。现在强行改成true貌似可以测试效果，除了奇数次打开会出现努力加载中。。。再研究一下。。

**Comment by cmzy** [comment]
麻烦提供下机型，rom型号，os版本等信息，以及把日志打开后的运行logcat日志。

**Comment by codehz** [comment]
机型小米NOTE LTE/Droid4x  WIN
rom 小米是秋大的5.1.1 Droid4X是只知道是4.2.2
现在的情况是，修改mEnable为true，不修改Provider的authorities的情况下，正常运行，但是在别的应用中使用（修改mEnable为true），修改authorities就会出现奇数次打开卡在努力加载中，不修改authorities则会不兼容。。奇葩的BUG...
下面是不修改mEnable的logcat
```
08-30 22:21:29.320    4230-4230/? I/art﹕ Late-enabling -Xcheck:jni
08-30 22:21:30.462    4230-4272/com.example.TestPlugin W/PackageParser﹕ Unknown element under <application>: enable-feature at /storage/emulated/0/com.bittorrent.sync.apk Binary XML file line #54
08-30 22:21:30.463    4230-4272/com.example.TestPlugin W/PackageParser﹕ No actions in intent filter at /storage/emulated/0/com.bittorrent.sync.apk Binary XML file line #81
08-30 22:21:30.523    4230-4272/com.example.TestPlugin W/PackageParser﹕ Unknown element under <application>: enable-feature at /storage/emulated/0/android-google-release-1.4.65.apk Binary XML file line #55
08-30 22:21:30.524    4230-4272/com.example.TestPlugin W/PackageParser﹕ No actions in intent filter at /storage/emulated/0/android-google-release-1.4.65.apk Binary XML file line #86
08-30 22:21:30.736    4230-4230/com.example.TestPlugin W/ResourceType﹕ No package identifier when getting value for resource number 0x00000000
08-30 22:21:30.904    4230-4230/com.example.TestPlugin I/Timeline﹕ Timeline: Activity_idle id: android.os.BinderProxy@2f73e963 time:155228008
08-30 22:21:43.730    4230-4230/com.example.TestPlugin I/Timeline﹕ Timeline: Activity_launch_request id:com.klinker.android.sliding.sample time:155240833
08-30 22:21:43.731    4230-4230/com.example.TestPlugin D/AndroidRuntime﹕ Shutting down VM
08-30 22:21:43.768    4230-4230/com.example.TestPlugin E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.example.TestPlugin, PID: 4230
    android.content.ActivityNotFoundException: Unable to find explicit activity class {com.klinker.android.sliding.sample/com.klinker.android.sliding.sample.SampleActivity}; have you declared this activity in your AndroidManifest.xml?
            at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1777)
            at android.app.Instrumentation.execStartActivity(Instrumentation.java:1501)
            at android.app.Activity.startActivityForResult(Activity.java:3745)
            at android.app.Activity.startActivityForResult(Activity.java:3706)
            at android.support.v4.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:826)
            at android.support.v4.app.Fragment.startActivity(Fragment.java:896)
            at com.example.TestPlugin.InstalledFragment.onListItemClick(InstalledFragment.java:51)
            at com.example.TestPlugin.InstalledFragment$3$1.onClick(InstalledFragment.java:147)
            at android.view.View.performClick(View.java:4781)
            at android.view.View$PerformClick.run(View.java:19873)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
```
官方的案例修改mEnable后则正常运行，
```
08-30 22:22:53.378    6513-6513/? I/art﹕ Late-enabling -Xcheck:jni
08-30 22:22:54.440    6513-6561/com.example.TestPlugin W/PackageParser﹕ Unknown element under <application>: enable-feature at /storage/emulated/0/com.bittorrent.sync.apk Binary XML file line #54
08-30 22:22:54.443    6513-6561/com.example.TestPlugin W/PackageParser﹕ No actions in intent filter at /storage/emulated/0/com.bittorrent.sync.apk Binary XML file line #81
08-30 22:22:54.508    6513-6561/com.example.TestPlugin W/PackageParser﹕ Unknown element under <application>: enable-feature at /storage/emulated/0/android-google-release-1.4.65.apk Binary XML file line #55
08-30 22:22:54.509    6513-6561/com.example.TestPlugin W/PackageParser﹕ No actions in intent filter at /storage/emulated/0/android-google-release-1.4.65.apk Binary XML file line #86
08-30 22:22:54.753    6513-6513/com.example.TestPlugin W/ResourceType﹕ No package identifier when getting value for resource number 0x00000000
08-30 22:22:55.042    6513-6513/com.example.TestPlugin I/Timeline﹕ Timeline: Activity_idle id: android.os.BinderProxy@2f73e963 time:155312145
08-30 22:22:55.456    6513-6513/com.example.TestPlugin I/Timeline﹕ Timeline: Activity_launch_request id:com.example.TestPlugin time:155312559
```
在第三方应用中使用这个库，同样也要修改mEnable才能正常运行。。但是authorities必须改，而修改则会造成奇数次打开插件卡在正在加载。。。返回键按下后再打开则没这个问题。。。
还有编译环境是Windows 10 x64 build 10240
Android Studio 1.3
Gradle 1.2.3但可能编译官方案例使用的不是这个版本。。
compileSdkVersion 23

**Comment by codehz** [comment]
还有一点说明，我对源码的patch除了这个mEnable之外，还有IActivityManagerHook.java里将Singleton直接改成本地的，在尾部加了这段代码，建议作者在这种地方就不用这种系统隐藏API好了。。。毕竟这玩意实在没必要。。。反而增加了其他人编译的难度。
```
abstract class Singleton<T> {
    private T mInstance;

    protected abstract T create();

    public final T get() {
        synchronized (this) {
            if (mInstance == null) {
                mInstance = create();
            }
            return mInstance;
        }
    }
}
```

**Comment by xiaopengs** [comment]
codehz 说的靠谱 我也本地化了Singleton

**Comment by qihoo360github** [comment]
本地化Singleton不靠谱的。

**Comment by codehz** [comment]
我觉得，对于这么一个简单的Singleton，直接内联实现不很好吗。。。
```
FieldUtils.writeStaticField(cls, "gDefault", new Object() {
    private boolean first = true;

    protected void create() {
        Log.e(TAG, "Install ActivityManager 3 Hook  old=%s,new=%s", mOldObj, object);
        first = false;
    }
   public final Object get() {
        if (first) create();
        return object;
    }
});
```
貌似这个create现在只是为了调试。。。反正我没看出有什么使用系统的Singleton的理由。。..

**Comment by haiyongou** [comment]
@cmzy 修改hook 文件里面, mEnable为true, 确实是能正常启动插件, 否则报未注册Activity have you declared this activity in your AndroidManifest.xml?错误，看了代码分析，估计InstallHook 没启用。我用Nexus 4 测试的。

**Comment by codehz** [comment]
刚才研究了一下。可能真的必须使用系统的SIngleton，否则类型检查会出问题。。大概。。。

**Comment by qihoo360github** [comment]
@haiyongou 不要修改mEnable，我估计是你的SIngleton修改导致出问题了。

**Comment by codehz** [comment]
嗯，刚才我就猜到是这恶原因了，能给个能用的sdk么。。。我sdk源代码没下载。。

**Comment by cmzy** [comment]
@codehz  我稍后会提交代码上去就可以编译了。

**Comment by haiyongou** [comment]
@qihoo360github 嗯，确实是Singleton 改成本地的了
public abstract class SingletonUtils<T> {
    private T instance;
    protected abstract T newInstance();
    public final T getInstance() {
        if (instance == null) {
            synchronized (SingletonUtils.class) {
                if (instance == null) {
                    instance = newInstance();
                }
            }
        }
        return instance;
    }
}

**Comment by codehz** [comment]
我觉得把消除了隐藏标签的sdk包含进项目里不是一个好主意，因为有的项目要求不同版本的sdk。有别的方法能解决吗。。。。是不是可以动态生成Singleton的子类呢

**Comment by cmzy** [comment]
@codehz  不用那么复杂的。

**Comment by truelizhi** [comment]
你好，我也在用这个框架，根据引导编译并运行之后也发现了“奇数次打不开，偶数次才可以打开”的BUG。。不知道是什么原因呢？

**Comment by xiaopengs** [comment]
BUG 有点多  能完善编译方式吗

**Comment by LLbgithub** [comment]
我发现横竖屏切换的时候原来配置的android:configChanges="orientation|keyboardHidden|screenSize"不管用了，请问是BUG么？

**Comment by cmzy** [comment]
编译问题fix了，再试试。

**Comment by haiyongou** [comment]
good !

**Comment by LLbgithub** [comment]
@truelizhi 我也遇到了一个这样的问题奇数次打开，偶数次打不开的情况。

**Comment by cmzy** [comment]
@LLbgithub 我fix后你用最新的代码试试呢？我这里是没问题的。

**Comment by cmzy** [comment]
fix，close，新问题请重新提交bug。

**Comment by yongganShaonian** [comment]
启动插件时Activity时，宿主设置的Intent无法传递到插件？
