### ISSUE TITLE
Requires android.permission.INTERACT_ACROSS_USERS_FULL

### ISSUE THREAD

**Issue by zourb** [Qihoo360/DroidPlugin#43]
18:24:34.933    7015-7702/? E/DatabaseUtils﹕ Writing exception to parcel
    java.lang.SecurityException: Permission Denial: get/set setting for user asks to run as user -2 but is calling from user 0; this requires android.permission.INTERACT_ACROSS_USERS_FULL
            at com.android.server.am.ActivityManagerService.handleIncomingUser(ActivityManagerService.java:13077)
            at android.app.ActivityManager.handleIncomingUser(ActivityManager.java:2021)
            at com.android.providers.settings.SettingsProvider.callFromPackage(SettingsProvider.java:577)
            at android.content.ContentProvider$Transport.call(ContentProvider.java:279)
            at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:273)
            at android.os.Binder.execTransact(Binder.java:388)
            at dalvik.system.NativeStart.run(Native Method)

**Comment by zourb** [comment]
机型： 三星Note3，N9006

**Comment by cmzy** [comment]
操作步骤是啥？

**Comment by cmzy** [comment]
fixed and closed.

**Comment by cxchenxin** [comment]
这个问题解决了吗？ 机型：三星G7109   android4.3出现最多。

**Comment by KelvinEng** [comment]
Requires android.permission.INTERACT_ACROSS_USERS_FULL 我也遇到了这样的问题

可否提供解决方法？ Android sdk level 19

05-22 12:56:01.229 2346-4025/? E/DatabaseUtils: Writing exception to parcel
    java.lang.SecurityException: Permission Denial: get/set setting for user asks to run as user -2 but is calling from user 0; this requires android.permission.INTERACT_ACROSS_USERS_FULL
        at com.android.server.am.ActivityManagerService.handleIncomingUser(ActivityManagerService.java:13140)
