### ISSUE TITLE
在米4 4.4版本和红米4.2.2上总是出现停留在加载页面，表现为基数次都会停留在加载页面

### ISSUE THREAD

**Issue by tjianli** [Qihoo360/DroidPlugin#51]
一个很简单的测试demo，apk下载地址 http://www.pgyer.com/VCVx
不知道为什么2个log文件提交不上去，贴出来了只好

log1:
2015-10-12 02:36:06.234 9295-10329/? I/PluginCallback handleMessage(107,RESUME_ACTIVITY) cost 0 ms
2015-10-12 02:36:06.695 9295-10329/? I/HookedMethodHandler doHookInner method(com.android.internal.view.IInputMethodManager.windowGainedFocus) cost 6 ms
2015-10-12 02:36:08.942 9295-10329/? I/HookedMethodHandler doHookInner method(android.app.IActivityManager.getRunningAppProcesses) cost 21 ms
2015-10-12 02:36:08.983 9295-10329/? I/IPackageManagerHookHandle getPackageInfo(com.example.TestPlugin) fail,pkginfo is null
2015-10-12 02:36:09.009 9295-10329/? I/HookedMethodHandler doHookInner method(android.app.IActivityManager.startActivity) cost 92 ms
2015-10-12 02:36:09.025 9295-10329/? I/PluginCallback handleMessage(101,PAUSE_ACTIVITY) cost 1 ms
2015-10-12 02:36:09.168 9295-10329/? I/PluginCallback handleMessage(115,SERVICE_ARGS) cost 0 ms
2015-10-12 02:36:09.208 9295-10329/? I/HookedMethodHandler doHookInner method(android.app.IActivityManager.getRunningAppProcesses) cost 6 ms
2015-10-12 02:36:09.415 9295-10329/? I/PluginCallback handleMessage(104,STOP_ACTIVITY_HIDE) cost 0 ms
2015-10-12 02:36:12.181 9295-10329/? I/PluginCallback handleMessage(140,TRIM_MEMORY) cost 1 ms

log2:
2015-10-12 02:36:09.096 9727-10329/? E/PluginHelper getMainLooper MessageQueue.IdleHandler:{ when=-30ms what=100 obj=ActivityRecord{42dc87b8 token=android.os.BinderProxy@42dc7f30 {com.example.TestPlugin/com.morgoo.droidplugin.stub.ActivityStub$StandardP02}} target=android.app.ActivityThread$H }
2015-10-12 02:36:09.124 9727-10329/? W/IWindowManagerBinderHook onInstall writeStaticField to sWindowManager fail
java.lang.ClassNotFoundException: com.android.internal.policy.PhoneWindow$WindowManagerHolder
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:251)
	at java.lang.Class.forName(Class.java:216)
	at com.morgoo.droidplugin.hook.binder.IWindowManagerBinderHook.onInstall(IWindowManagerBinderHook.java:72)
	at com.morgoo.droidplugin.hook.HookFactory.installHook(HookFactory.java:104)
	at com.morgoo.droidplugin.hook.HookFactory.installHook(HookFactory.java:123)
	at com.morgoo.droidplugin.core.PluginProcessManager.installHook(PluginProcessManager.java:297)
	at com.morgoo.droidplugin.PluginHelper.initPlugin(PluginHelper.java:76)
	at com.morgoo.droidplugin.PluginHelper.applicationOnCreate(PluginHelper.java:63)
	at com.morgoo.droidplugin.PluginApplication.onCreate(PluginApplication.java:45)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4374)
	at android.app.ActivityThread.access$1500(ActivityThread.java:141)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1264)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5049)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NoClassDefFoundError: com/android/internal/policy/PhoneWindow$WindowManagerHolder
	... 22 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.internal.policy.PhoneWindow$WindowManagerHolder" on path: DexPathList[[zip file "/data/app/com.example.TestPlugin-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.example.TestPlugin-2, /vendor/lib, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
	... 22 more

2015-10-12 02:36:09.149 9727-10329/? I/IActivityManagerHook Install ActivityManager Hook 2 old=android.app.ActivityManagerProxy@42dc6058,new=android.app.ActivityManagerProxy@42dc6058
2015-10-12 02:36:09.150 9727-10329/? E/IActivityManagerHook Install ActivityManager 3 Hook  old=android.app.ActivityManagerProxy@42dc6058,new=android.app.ActivityManagerProxy@42dc6058
2015-10-12 02:36:09.151 9727-10329/? I/PluginCallbackHook PluginCallbackHook has installed
2015-10-12 02:36:09.153 9727-10329/? I/InstrumentationHook Install Instrumentation Hook old=android.app.Instrumentation android.app.ActivityThread.mInstrumentation,new=com.morgoo.droidplugin.hook.handle.PluginInstrumentation@42e8d2e0
2015-10-12 02:36:09.172 9727-10329/? I/PluginHelper Init plugin in process cost 79 ms
2015-10-12 02:36:09.173 9727-10329/? I/PluginCallback handleMessage(100,LAUNCH_ACTIVITY) cost 0 ms
2015-10-12 02:36:09.175 9727-10329/? W/IWindowManagerBinderHook fixWindowManagerHook writeStaticField to sWindowManager fail
java.lang.ClassNotFoundException: com.android.internal.policy.impl.MiuiPhoneWindow$WindowManagerHolder
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:251)
	at java.lang.Class.forName(Class.java:216)
	at com.morgoo.droidplugin.hook.binder.IWindowManagerBinderHook.fixWindowManagerHook(IWindowManagerBinderHook.java:83)
	at com.morgoo.droidplugin.hook.handle.PluginInstrumentation.callActivityOnCreate(PluginInstrumentation.java:68)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2156)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2241)
	at android.app.ActivityThread.access$800(ActivityThread.java:141)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1204)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5049)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NoClassDefFoundError: com/android/internal/policy/impl/MiuiPhoneWindow$WindowManagerHolder
	... 17 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.internal.policy.impl.MiuiPhoneWindow$WindowManagerHolder" on path: DexPathList[[zip file "/data/app/com.example.TestPlugin-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.example.TestPlugin-2, /vendor/lib, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
	... 17 more

2015-10-12 02:36:09.199 9727-10329/? I/PluginManager onServiceConnected connected OK!
2015-10-12 02:36:09.209 9727-10329/? I/PluginCallbackHook PluginCallbackHook has installed,skip
2015-10-12 02:36:09.210 9727-10329/? I/InstrumentationHook Instrumentation has installed,skip
2015-10-12 02:36:09.211 9727-10329/? I/PluginManager PluginManager ready!
2015-10-12 02:36:11.229 9727-10329/? I/PluginCallback handleMessage(101,PAUSE_ACTIVITY) cost 0 ms
2015-10-12 02:36:12.161 9727-10329/? I/PluginCallback handleMessage(104,STOP_ACTIVITY_HIDE) cost 0 ms
2015-10-12 02:36:12.183 9727-10329/? I/PluginCallback handleMessage(140,TRIM_MEMORY) cost 1 ms
2015-10-12 02:36:19.105 9727-10329/? I/PluginCallback handleMessage(132,ENABLE_JIT) cost 0 ms

**Comment by cmzy** [comment]
日志不全啊？github可以提交文件的，你提交上来试试。

**Comment by tjianli** [comment]
提交文件，提示Something went really wrong, and we can’t process that file. 人品问题吧估计
我比对了下，复制的文本，是生成的2个log文件全部内容

运行的是TestPlugin，安装测试apk后，直接点击运行，就出现之前说的情况

**Comment by tjianli** [comment]
今天把360手机助手卸载了，直接运行project居然不存在上面提到的问题了，来回尝试了几次，发现只要修改了
<provider
    android:name="com.morgoo.droidplugin.stub.ContentProviderStub$StubP00"
    android:authorities="com.morgoo.droidplugin_stub_P00"
    android:exported="false"
    android:label="@string/stub_name_povider" />
里面的authorities，就会出问题，我是批量替换的，都改成了
<provider
    android:name="com.morgoo.droidplugin.stub.ContentProviderStub$StubP00"
    android:authorities="com.test.droidplugin_stub_P00"
    android:exported="false"
    android:label="@string/stub_name_povider" />
其他地方没做改动
但是看reademe 这个地方是可以修改的啊。。。。。？？？？？

**Comment by cmzy** [comment]
全局搜索替换吗？

**Comment by tjianli** [comment]
在Libraries\DroidPlugin\AndroidManifest.xml，里面全局搜索替换

**Comment by cmzy** [comment]
还有一个地方，我文档写漏了。你看下。我已经提交了。
