### ISSUE TITLE
老是报这个错误java.lang.ClassNotFoundException: android.view.IGraphicsStats$Stub，怎么回事

### ISSUE THREAD

**Issue by 455586841** [Qihoo360/DroidPlugin#75]
手机：小米4c，Android 5.1.1
{"versionName":"2.4.6","versionCode":25,"osVersion":"5.1.1","sdkVersion":"22","phoneType":"Mi-4c","brand":"Xiaomi","memoryTotal":"-1264.65MB","manufacturer":"Xiaomi","wifiMac":"20:82:c0:6d:bc:a8","systemRealtime":"2天57小时28分","CPU_ABI":"arm64-v8a","CPU_ABI2":"","widthPixels":1080,"heightPixels":1920,"xdpi":449.7040100097656,"ydpi":447.4119873046875,"densityDpi":480,"density":3,"scaledDensity":3}
错误信息:
11-17 09:54:39.682 16749-16749/com.tydic.android.plugin.platform.app.develop E/PluginHelper: getMainLooper MessageQueue.IdleHandler:{ when=-48ms what=100 obj=ActivityRecord{3543430 token=android.os.BinderProxy@1fe108a9 {com.tydic.android.plugin.platform.app.develop/com.tydic.android.plugin.platform.app.activity.SplashActivity}} target=android.app.ActivityThread$H }
11-17 09:54:39.742 16749-16749/com.tydic.android.plugin.platform.app.develop E/HookFactory: installHook com.morgoo.droidplugin.hook.binder.IGraphicsStatsBinderHook@27306e19 error
11-17 09:54:39.742 16749-16749/com.tydic.android.plugin.platform.app.develop E/HookFactory: java.lang.ClassNotFoundException: android.view.IGraphicsStats$Stub
11-17 09:54:39.742 16749-16749/com.tydic.android.plugin.platform.app.develop E/HookFactory:     at java.lang.Class.classForName(Native Method)
11-17 09:54:39.742 16749-16749/com.tydic.android.plugin.platform.app.develop E/HookFactory:     at java.lang.Class.forName(Class.java:309)
11-17 09:54:39.742 16749-16749/com.tydic.android.plugin.platform.app.develop E/HookFactory:     at java.lang.Class.forName(Class.java:273)
11-17 09:54:39.742 16749-16749/com.tydic.android.plugin.platform.app.develop E/HookFactory:     at com.morgoo.helper.compat.IGraphicsStatsCompat.asInterface(IGraphicsStatsCompat.java:46)
11-17 09:54:39.742 16749-16749/com.tydic.android.plugin.platform.app.develop E/HookFactory:     at com.morgoo.droidplugin.hook.binder.IGraphicsStatsBinderHook.getOldObj(IGraphicsStatsBinderHook.java:48)
11-17 09:54:39.742 16749-16749/com.tydic.android.plugin.platform.app.develop E/HookFactory:     at com.morgoo.droidplugin.hook.binder.BinderHook.onInstall(BinderHook.java:96)
11-17 09:54:39.742 16749-16749/com.tydic.android.plugin.platform.app.develop E/HookFactory:     at com.morgoo.droidplugin.hook.HookFactory.installHook(HookFactory.java:105)
11-17 09:54:39.742 16749-16749/com.tydic.android.plugin.platform.app.develop E/HookFactory:     at com.morgoo.droidplugin.hook.HookFactory.installHook(HookFactory.java:126)
11-17 09:54:39.742 16749-16749/com.tydic.android.plugin.platform.app.develop E/HookFactory:     at com.morgoo.droidplugin.core.PluginProcessManager.installHook(PluginProcessManager.java:297)
11-17 09:54:39.742 16749-16749/com.tydic.android.plugin.platform.app.develop E/HookFactory:     at com.morgoo.droidplugin.PluginHelper.initPlugin(PluginHelper.java:76)
11-17 09:54:39.742 16749-16749/com.tydic.android.plugin.platform.app.develop E/HookFactory:     at com.morgoo.droidplugin.PluginHelper.applicationOnCreate(PluginHelper.java:63)
11-17 09:54:39.742 16749-16749/com.tydic.android.plugin.platform.app.develop E/HookFactory:     at com.morgoo.droidplugin.PluginApplication.onCreate(PluginApplication.java:45)
11-17 09:54:39.742 16749-16749/com.tydic.android.plugin.platform.app.develop E/HookFactory:     at com.tydic.android.plugin.platform.library.PluginPlatformApplication.onCreate(PluginPlatformApplication.java:22)
11-17 09:54:39.742 16749-16749/com.tydic.android.plugin.platform.app.develop E/HookFactory:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
11-17 09:54:39.742 16749-16749/com.tydic.android.plugin.platform.app.develop E/HookFactory:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4569)
11-17 09:54:39.742 16749-16749/com.tydic.android.plugin.platform.app.develop E/HookFactory:     at android.app.ActivityThread.access$1500(ActivityThread.java:154)
11-17 09:54:39.742 16749-16749/com.tydic.android.plugin.platform.app.develop E/HookFactory:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1369)
11-17 09:54:39.742 16749-16749/com.tydic.android.plugin.platform.app.develop E/HookFactory:     at android.os.Handler.dispatchMessage(Handler.java:102)
11-17 09:54:39.742 16749-16749/com.tydic.android.plugin.platform.app.develop E/HookFactory:     at android.os.Looper.loop(Looper.java:135)
11-17 09:54:39.742 16749-16749/com.tydic.android.plugin.platform.app.develop E/HookFactory:     at android.app.ActivityThread.main(ActivityThread.java:5275)
11-17 09:54:39.742 16749-16749/com.tydic.android.plugin.platform.app.develop E/HookFactory:     at java.lang.reflect.Method.invoke(Native Method)
11-17 09:54:39.742 16749-16749/com.tydic.android.plugin.platform.app.develop E/HookFactory:     at java.lang.reflect.Method.invoke(Method.java:372)
11-17 09:54:39.742 16749-16749/com.tydic.android.plugin.platform.app.develop E/HookFactory:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:910)
11-17 09:54:39.742 16749-16749/com.tydic.android.plugin.platform.app.develop E/HookFactory:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:705)
11-17 09:54:39.742 16749-16749/com.tydic.android.plugin.platform.app.develop E/HookFactory:  Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.IGraphicsStats$Stub" on path: DexPathList[[zip file "/data/app/com.tydic.android.plugin.platform.app.develop-2/base.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]
11-17 09:54:39.742 16749-16749/com.tydic.android.plugin.platform.app.develop E/HookFactory:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
11-17 09:54:39.742 16749-16749/com.tydic.android.plugin.platform.app.develop E/HookFactory:     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
11-17 09:54:39.742 16749-16749/com.tydic.android.plugin.platform.app.develop E/HookFactory:     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
11-17 09:54:39.742 16749-16749/com.tydic.android.plugin.platform.app.develop E/HookFactory:     at java.lang.Class.classForName(Native Method) 
11-17 09:54:39.742 16749-16749/com.tydic.android.plugin.platform.app.develop E/HookFactory:     at java.lang.Class.forName(Class.java:309) 
11-17 09:54:39.742 16749-16749/com.tydic.android.plugin.platform.app.develop E/HookFactory:     at java.lang.Class.forName(Class.java:273) 
11-17 09:54:39.742 16749-16749/com.tydic.android.plugin.platform.app.develop E/HookFactory:     at com.morgoo.helper.compat.IGraphicsStatsCompat.asInterface(IGraphicsStatsCompat.java:46) 
11-17 09:54:39.742 16749-16749/com.tydic.android.plugin.platform.app.develop E/HookFactory:     at com.morgoo.droidplugin.hook.binder.IGraphicsStatsBinderHook.getOldObj(IGraphicsStatsBinderHook.java:48) 
11-17 09:54:39.742 16749-16749/com.tydic.android.plugin.platform.app.develop E/HookFactory:     at com.morgoo.droidplugin.hook.binder.BinderHook.onInstall(BinderHook.java:96) 
11-17 09:54:39.742 16749-16749/com.tydic.android.plugin.platform.app.develop E/HookFactory:     at com.morgoo.droidplugin.hook.HookFactory.installHook(HookFactory.java:105) 
11-17 09:54:39.742 16749-16749/com.tydic.android.plugin.platform.app.develop E/HookFactory:     at com.morgoo.droidplugin.hook.HookFactory.installHook(HookFactory.java:126) 
11-17 09:54:39.742 16749-16749/com.tydic.android.plugin.platform.app.develop E/HookFactory:     at com.morgoo.droidplugin.core.PluginProcessManager.installHook(PluginProcessManager.java:297) 
11-17 09:54:39.742 16749-16749/com.tydic.android.plugin.platform.app.develop E/HookFactory:     at com.morgoo.droidplugin.PluginHelper.initPlugin(PluginHelper.java:76) 
11-17 09:54:39.742 16749-16749/com.tydic.android.plugin.platform.app.develop E/HookFactory:     at com.morgoo.droidplugin.PluginHelper.applicationOnCreate(PluginHelper.java:63) 
11-17 09:54:39.742 16749-16749/com.tydic.android.plugin.platform.app.develop E/HookFactory:     at com.morgoo.droidplugin.PluginApplication.onCreate(PluginApplication.java:45) 
11-17 09:54:39.742 16749-16749/com.tydic.android.plugin.platform.app.develop E/HookFactory:     at com.tydic.android.plugin.platform.library.PluginPlatformApplication.onCreate(PluginPlatformApplication.java:22) 
11-17 09:54:39.742 16749-16749/com.tydic.android.plugin.platform.app.develop E/HookFactory:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012) 
11-17 09:54:39.742 16749-16749/com.tydic.android.plugin.platform.app.develop E/HookFactory:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4569) 
11-17 09:54:39.742 16749-16749/com.tydic.android.plugin.platform.app.develop E/HookFactory:     at android.app.ActivityThread.access$1500(ActivityThread.java:154) 
11-17 09:54:39.742 16749-16749/com.tydic.android.plugin.platform.app.develop E/HookFactory:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1369) 
11-17 09:54:39.742 16749-16749/com.tydic.android.plugin.platform.app.develop E/HookFactory:     at android.os.Handler.dispatchMessage(Handler.java:102) 
11-17 09:54:39.742 16749-16749/com.tydic.android.plugin.platform.app.develop E/HookFactory:     at android.os.Looper.loop(Looper.java:135) 
11-17 09:54:39.742 16749-16749/com.tydic.android.plugin.platform.app.develop E/HookFactory:     at android.app.ActivityThread.main(ActivityThread.java:5275) 
11-17 09:54:39.742 16749-16749/com.tydic.android.plugin.platform.app.develop E/HookFactory:     at java.lang.reflect.Method.invoke(Native Method) 
11-17 09:54:39.742 16749-16749/com.tydic.android.plugin.platform.app.develop E/HookFactory:     at java.lang.reflect.Method.invoke(Method.java:372) 
11-17 09:54:39.742 16749-16749/com.tydic.android.plugin.platform.app.develop E/HookFactory:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:910) 
11-17 09:54:39.742 16749-16749/com.tydic.android.plugin.platform.app.develop E/HookFactory:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:705) 
11-17 09:54:39.742 16749-16749/com.tydic.android.plugin.platform.app.develop E/HookFactory: 	Suppressed: java.lang.ClassNotFoundException: android.view.IGraphicsStats$Stub
11-17 09:54:39.742 16749-16749/com.tydic.android.plugin.platform.app.develop E/HookFactory:     at java.lang.Class.classForName(Native Method)
11-17 09:54:39.742 16749-16749/com.tydic.android.plugin.platform.app.develop E/HookFactory:     at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
11-17 09:54:39.742 16749-16749/com.tydic.android.plugin.platform.app.develop E/HookFactory:     at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
11-17 09:54:39.742 16749-16749/com.tydic.android.plugin.platform.app.develop E/HookFactory:     at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
11-17 09:54:39.742 16749-16749/com.tydic.android.plugin.platform.app.develop E/HookFactory:     		... 25 more
11-17 09:54:39.742 16749-16749/com.tydic.android.plugin.platform.app.develop E/HookFactory:  Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
11-17 09:54:39.832 16749-16749/com.tydic.android.plugin.platform.app.develop E/IActivityManagerHook: Install ActivityManager 3 Hook  old=android.app.ActivityManagerProxy@1359024,new=android.app.ActivityManagerProxy@1359024
11-17 09:54:42.102 16749-16749/com.tydic.android.plugin.platform.app.develop E/PluginCallback: handleLaunchActivity targetIntent==null
11-17 09:54:43.982 16749-16749/com.tydic.android.plugin.platform.app.develop E/PluginCallback: handleLaunchActivity targetIntent==null

**Comment by L-ios** [comment]
android.view.IGraphicsStats是在6.0中才会提供的，所以改一下就好了
