### ISSUE TITLE
结束插件时候，process打印异常的原因

### ISSUE THREAD

**Issue by motcwang** [Qihoo360/DroidPlugin#81]
```java
java.lang.RuntimeException
11-23 14:27:13.735 1425-1461/com.example.TestPlugin I/Process:     at android.os.Process.killProcess(Process.java:957)
11-23 14:27:13.735 1425-1461/com.example.TestPlugin I/Process:     at com.morgoo.droidplugin.am.MyActivityManagerService.doGc(MyActivityManagerService.java:452)
11-23 14:27:13.735 1425-1461/com.example.TestPlugin I/Process:     at com.morgoo.droidplugin.am.MyActivityManagerService.runProcessGC(MyActivityManagerService.java:429)
11-23 14:27:13.735 1425-1461/com.example.TestPlugin I/Process:     at com.morgoo.droidplugin.am.MyActivityManagerService.onActivityDestory(MyActivityManagerService.java:241)
11-23 14:27:13.735 1425-1461/com.example.TestPlugin I/Process:     at com.morgoo.droidplugin.pm.IPluginManagerImpl.onActivityDestory(IPluginManagerImpl.java:1322)
11-23 14:27:13.735 1425-1461/com.example.TestPlugin I/Process:     at com.morgoo.droidplugin.pm.IPluginManager$Stub.onTransact(IPluginManager.java:730)
11-23 14:27:13.735 1425-1461/com.example.TestPlugin I/Process:     at android.os.Binder.execTransact(Binder.java:404)
11-23 14:27:13.735 1425-1461/com.example.TestPlugin I/Process:     at dalvik.system.NativeStart.run(Native Method)
11-23 14:27:13.735 1425-1461/com.example.TestPlugin I/Process: Sending signal. PID: 1727 SIG: 9
```

**Comment by cmzy** [comment]
能否更详细一点？

**Comment by motcwang** [comment]
打开插件APK，然后点击back，就会打印
应该是back时候判断执行killProcess的问题吧？

**Comment by cmzy** [comment]
我这没复现啊？

**Comment by motcwang** [comment]
我用的锤子跑的示例代码，每次都可重现
刚才用其它手机测了一下，只有锤子出现了这个问题
