### ISSUE TITLE
Question：自动脚本

### ISSUE THREAD

**Issue by luoqii** [Qihoo360/DroidPlugin#89]
请教一个问题： 我使用一个脚本，自动生成用于宿主的stub activity, service,... ... 
并ActivityStub类删除，同时调整代码中对ActivityStub的依赖，删除AndroidManifest.xml
中的相应声明，加上脚本生成的activity,service,.. 的声明，这时会出现：
   安装的插件第一次卡在”努力加载中“, 但吊诡的是之后就好了？

代码里是对ActivityStub有某种强的假定存在吗？还是仅仅依赖AndroidManifest.xml里的声明？

谢谢
code see https://github.com/luoqii/DroidPlugin/tree/add_script

Stacktrace:
11-25 17:17:33.678 9234-9234/? I/art: Late-enabling -Xcheck:jni
11-25 17:17:33.748 9234-9234/com.cibn.tv:PluginP3 E/PluginHelper: getMainLooper MessageQueue.IdleHandler:{ when=-20ms what=100 obj=ActivityRecord{3bb72641 token=android.os.BinderProxy@11e947e6 {com.cibn.tv/com.morgoo.droidplugin.stub.Stub$Activity_P3SingleTask1}} target=android.app.ActivityThread$H }
11-25 17:17:33.835 9234-9234/com.cibn.tv:PluginP3 W/IWindowManagerBinderHook: onInstall writeStaticField to sWindowManager fail
11-25 17:17:33.835 9234-9234/com.cibn.tv:PluginP3 W/IWindowManagerBinderHook: java.lang.ClassNotFoundException: com.android.internal.policy.PhoneWindow$WindowManagerHolder
11-25 17:17:33.835 9234-9234/com.cibn.tv:PluginP3 W/IWindowManagerBinderHook:     at java.lang.Class.classForName(Native Method)
11-25 17:17:33.835 9234-9234/com.cibn.tv:PluginP3 W/IWindowManagerBinderHook:     at java.lang.Class.forName(Class.java:309)
11-25 17:17:33.835 9234-9234/com.cibn.tv:PluginP3 W/IWindowManagerBinderHook:     at java.lang.Class.forName(Class.java:273)
11-25 17:17:33.835 9234-9234/com.cibn.tv:PluginP3 W/IWindowManagerBinderHook:     at com.morgoo.droidplugin.hook.binder.IWindowManagerBinderHook.onInstall(IWindowManagerBinderHook.java:72)
11-25 17:17:33.835 9234-9234/com.cibn.tv:PluginP3 W/IWindowManagerBinderHook:     at com.morgoo.droidplugin.hook.HookFactory.installHook(HookFactory.java:105)
11-25 17:17:33.835 9234-9234/com.cibn.tv:PluginP3 W/IWindowManagerBinderHook:     at com.morgoo.droidplugin.hook.HookFactory.installHook(HookFactory.java:124)
11-25 17:17:33.835 9234-9234/com.cibn.tv:PluginP3 W/IWindowManagerBinderHook:     at com.morgoo.droidplugin.core.PluginProcessManager.installHook(PluginProcessManager.java:296)
11-25 17:17:33.835 9234-9234/com.cibn.tv:PluginP3 W/IWindowManagerBinderHook:     at com.morgoo.droidplugin.PluginHelper.initPlugin(PluginHelper.java:76)
11-25 17:17:33.835 9234-9234/com.cibn.tv:PluginP3 W/IWindowManagerBinderHook:     at com.morgoo.droidplugin.PluginHelper.applicationOnCreate(PluginHelper.java:63)
11-25 17:17:33.835 9234-9234/com.cibn.tv:PluginP3 W/IWindowManagerBinderHook:     at com.morgoo.droidplugin.PluginApplication.onCreate(PluginApplication.java:45)
11-25 17:17:33.835 9234-9234/com.cibn.tv:PluginP3 W/IWindowManagerBinderHook:     at com.example.TestPlugin.App.onCreate(App.java:23)
11-25 17:17:33.835 9234-9234/com.cibn.tv:PluginP3 W/IWindowManagerBinderHook:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
11-25 17:17:33.835 9234-9234/com.cibn.tv:PluginP3 W/IWindowManagerBinderHook:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4553)
11-25 17:17:33.835 9234-9234/com.cibn.tv:PluginP3 W/IWindowManagerBinderHook:     at android.app.ActivityThread.access$1500(ActivityThread.java:151)
11-25 17:17:33.835 9234-9234/com.cibn.tv:PluginP3 W/IWindowManagerBinderHook:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
11-25 17:17:33.835 9234-9234/com.cibn.tv:PluginP3 W/IWindowManagerBinderHook:     at android.os.Handler.dispatchMessage(Handler.java:102)
11-25 17:17:33.835 9234-9234/com.cibn.tv:PluginP3 W/IWindowManagerBinderHook:     at android.os.Looper.loop(Looper.java:135)
11-25 17:17:33.835 9234-9234/com.cibn.tv:PluginP3 W/IWindowManagerBinderHook:     at android.app.ActivityThread.main(ActivityThread.java:5254)
11-25 17:17:33.835 9234-9234/com.cibn.tv:PluginP3 W/IWindowManagerBinderHook:     at java.lang.reflect.Method.invoke(Native Method)
11-25 17:17:33.835 9234-9234/com.cibn.tv:PluginP3 W/IWindowManagerBinderHook:     at java.lang.reflect.Method.invoke(Method.java:372)
11-25 17:17:33.835 9234-9234/com.cibn.tv:PluginP3 W/IWindowManagerBinderHook:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
11-25 17:17:33.835 9234-9234/com.cibn.tv:PluginP3 W/IWindowManagerBinderHook:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
11-25 17:17:33.835 9234-9234/com.cibn.tv:PluginP3 W/IWindowManagerBinderHook:  Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.internal.policy.PhoneWindow$WindowManagerHolder" on path: DexPathList[[zip file "/data/app/com.cibn.tv-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
11-25 17:17:33.835 9234-9234/com.cibn.tv:PluginP3 W/IWindowManagerBinderHook:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
11-25 17:17:33.835 9234-9234/com.cibn.tv:PluginP3 W/IWindowManagerBinderHook:     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
11-25 17:17:33.835 9234-9234/com.cibn.tv:PluginP3 W/IWindowManagerBinderHook:     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
11-25 17:17:33.835 9234-9234/com.cibn.tv:PluginP3 W/IWindowManagerBinderHook:     at java.lang.Class.classForName(Native Method) 
11-25 17:17:33.835 9234-9234/com.cibn.tv:PluginP3 W/IWindowManagerBinderHook:     at java.lang.Class.forName(Class.java:309) 
11-25 17:17:33.835 9234-9234/com.cibn.tv:PluginP3 W/IWindowManagerBinderHook:     at java.lang.Class.forName(Class.java:273) 
11-25 17:17:33.835 9234-9234/com.cibn.tv:PluginP3 W/IWindowManagerBinderHook:     at com.morgoo.droidplugin.hook.binder.IWindowManagerBinderHook.onInstall(IWindowManagerBinderHook.java:72) 
11-25 17:17:33.835 9234-9234/com.cibn.tv:PluginP3 W/IWindowManagerBinderHook:     at com.morgoo.droidplugin.hook.HookFactory.installHook(HookFactory.java:105) 
11-25 17:17:33.835 9234-9234/com.cibn.tv:PluginP3 W/IWindowManagerBinderHook:     at com.morgoo.droidplugin.hook.HookFactory.installHook(HookFactory.java:124) 
11-25 17:17:33.835 9234-9234/com.cibn.tv:PluginP3 W/IWindowManagerBinderHook:     at com.morgoo.droidplugin.core.PluginProcessManager.installHook(PluginProcessManager.java:296) 
11-25 17:17:33.835 9234-9234/com.cibn.tv:PluginP3 W/IWindowManagerBinderHook:     at com.morgoo.droidplugin.PluginHelper.initPlugin(PluginHelper.java:76) 
11-25 17:17:33.835 9234-9234/com.cibn.tv:PluginP3 W/IWindowManagerBinderHook:     at com.morgoo.droidplugin.PluginHelper.applicationOnCreate(PluginHelper.java:63) 
11-25 17:17:33.835 9234-9234/com.cibn.tv:PluginP3 W/IWindowManagerBinderHook:     at com.morgoo.droidplugin.PluginApplication.onCreate(PluginApplication.java:45) 
11-25 17:17:33.835 9234-9234/com.cibn.tv:PluginP3 W/IWindowManagerBinderHook:     at com.example.TestPlugin.App.onCreate(App.java:23) 
11-25 17:17:33.835 9234-9234/com.cibn.tv:PluginP3 W/IWindowManagerBinderHook:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012) 
11-25 17:17:33.835 9234-9234/com.cibn.tv:PluginP3 W/IWindowManagerBinderHook:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4553) 
11-25 17:17:33.835 9234-9234/com.cibn.tv:PluginP3 W/IWindowManagerBinderHook:     at android.app.ActivityThread.access$1500(ActivityThread.java:151) 
11-25 17:17:33.835 9234-9234/com.cibn.tv:PluginP3 W/IWindowManagerBinderHook:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364) 
11-25 17:17:33.835 9234-9234/com.cibn.tv:PluginP3 W/IWindowManagerBinderHook:     at android.os.Handler.dispatchMessage(Handler.java:102) 
11-25 17:17:33.835 9234-9234/com.cibn.tv:PluginP3 W/IWindowManagerBinderHook:     at android.os.Looper.loop(Looper.java:135) 
11-25 17:17:33.835 9234-9234/com.cibn.tv:PluginP3 W/IWindowManagerBinderHook:     at android.app.ActivityThread.main(ActivityThread.java:5254) 
11-25 17:17:33.835 9234-9234/com.cibn.tv:PluginP3 W/IWindowManagerBinderHook:     at java.lang.reflect.Method.invoke(Native Method) 
11-25 17:17:33.835 9234-9234/com.cibn.tv:PluginP3 W/IWindowManagerBinderHook:     at java.lang.reflect.Method.invoke(Method.java:372) 
11-25 17:17:33.835 9234-9234/com.cibn.tv:PluginP3 W/IWindowManagerBinderHook:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
11-25 17:17:33.835 9234-9234/com.cibn.tv:PluginP3 W/IWindowManagerBinderHook:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
11-25 17:17:33.835 9234-9234/com.cibn.tv:PluginP3 W/IWindowManagerBinderHook: 	Suppressed: java.lang.ClassNotFoundException: com.android.internal.policy.PhoneWindow$WindowManagerHolder
11-25 17:17:33.835 9234-9234/com.cibn.tv:PluginP3 W/IWindowManagerBinderHook:     at java.lang.Class.classForName(Native Method)
11-25 17:17:33.835 9234-9234/com.cibn.tv:PluginP3 W/IWindowManagerBinderHook:     at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
11-25 17:17:33.835 9234-9234/com.cibn.tv:PluginP3 W/IWindowManagerBinderHook:     at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
11-25 17:17:33.835 9234-9234/com.cibn.tv:PluginP3 W/IWindowManagerBinderHook:     at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
11-25 17:17:33.835 9234-9234/com.cibn.tv:PluginP3 W/IWindowManagerBinderHook:     		... 23 more
11-25 17:17:33.835 9234-9234/com.cibn.tv:PluginP3 W/IWindowManagerBinderHook:  Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
11-25 17:17:33.840 9234-9234/com.cibn.tv:PluginP3 E/HookFactory: installHook com.morgoo.droidplugin.hook.binder.IGraphicsStatsBinderHook@16097696 error
11-25 17:17:33.840 9234-9234/com.cibn.tv:PluginP3 E/HookFactory: java.lang.ClassNotFoundException: android.view.IGraphicsStats$Stub
11-25 17:17:33.840 9234-9234/com.cibn.tv:PluginP3 E/HookFactory:     at java.lang.Class.classForName(Native Method)
11-25 17:17:33.840 9234-9234/com.cibn.tv:PluginP3 E/HookFactory:     at java.lang.Class.forName(Class.java:309)
11-25 17:17:33.840 9234-9234/com.cibn.tv:PluginP3 E/HookFactory:     at java.lang.Class.forName(Class.java:273)
11-25 17:17:33.840 9234-9234/com.cibn.tv:PluginP3 E/HookFactory:     at com.morgoo.helper.compat.IGraphicsStatsCompat.asInterface(IGraphicsStatsCompat.java:46)
11-25 17:17:33.840 9234-9234/com.cibn.tv:PluginP3 E/HookFactory:     at com.morgoo.droidplugin.hook.binder.IGraphicsStatsBinderHook.getOldObj(IGraphicsStatsBinderHook.java:48)
11-25 17:17:33.840 9234-9234/com.cibn.tv:PluginP3 E/HookFactory:     at com.morgoo.droidplugin.hook.binder.BinderHook.onInstall(BinderHook.java:96)
11-25 17:17:33.840 9234-9234/com.cibn.tv:PluginP3 E/HookFactory:     at com.morgoo.droidplugin.hook.HookFactory.installHook(HookFactory.java:105)
11-25 17:17:33.840 9234-9234/com.cibn.tv:PluginP3 E/HookFactory:     at com.morgoo.droidplugin.hook.HookFactory.installHook(HookFactory.java:126)
11-25 17:17:33.840 9234-9234/com.cibn.tv:PluginP3 E/HookFactory:     at com.morgoo.droidplugin.core.PluginProcessManager.installHook(PluginProcessManager.java:296)
11-25 17:17:33.840 9234-9234/com.cibn.tv:PluginP3 E/HookFactory:     at com.morgoo.droidplugin.PluginHelper.initPlugin(PluginHelper.java:76)
11-25 17:17:33.840 9234-9234/com.cibn.tv:PluginP3 E/HookFactory:     at com.morgoo.droidplugin.PluginHelper.applicationOnCreate(PluginHelper.java:63)
11-25 17:17:33.840 9234-9234/com.cibn.tv:PluginP3 E/HookFactory:     at com.morgoo.droidplugin.PluginApplication.onCreate(PluginApplication.java:45)
11-25 17:17:33.840 9234-9234/com.cibn.tv:PluginP3 E/HookFactory:     at com.example.TestPlugin.App.onCreate(App.java:23)
11-25 17:17:33.840 9234-9234/com.cibn.tv:PluginP3 E/HookFactory:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
11-25 17:17:33.840 9234-9234/com.cibn.tv:PluginP3 E/HookFactory:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4553)
11-25 17:17:33.840 9234-9234/com.cibn.tv:PluginP3 E/HookFactory:     at android.app.ActivityThread.access$1500(ActivityThread.java:151)
11-25 17:17:33.840 9234-9234/com.cibn.tv:PluginP3 E/HookFactory:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
11-25 17:17:33.840 9234-9234/com.cibn.tv:PluginP3 E/HookFactory:     at android.os.Handler.dispatchMessage(Handler.java:102)
11-25 17:17:33.840 9234-9234/com.cibn.tv:PluginP3 E/HookFactory:     at android.os.Looper.loop(Looper.java:135)
11-25 17:17:33.840 9234-9234/com.cibn.tv:PluginP3 E/HookFactory:     at android.app.ActivityThread.main(ActivityThread.java:5254)
11-25 17:17:33.840 9234-9234/com.cibn.tv:PluginP3 E/HookFactory:     at java.lang.reflect.Method.invoke(Native Method)
11-25 17:17:33.840 9234-9234/com.cibn.tv:PluginP3 E/HookFactory:     at java.lang.reflect.Method.invoke(Method.java:372)
11-25 17:17:33.840 9234-9234/com.cibn.tv:PluginP3 E/HookFactory:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
11-25 17:17:33.840 9234-9234/com.cibn.tv:PluginP3 E/HookFactory:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
11-25 17:17:33.840 9234-9234/com.cibn.tv:PluginP3 E/HookFactory:  Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.IGraphicsStats$Stub" on path: DexPathList[[zip file "/data/app/com.cibn.tv-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
11-25 17:17:33.840 9234-9234/com.cibn.tv:PluginP3 E/HookFactory:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
11-25 17:17:33.840 9234-9234/com.cibn.tv:PluginP3 E/HookFactory:     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
11-25 17:17:33.840 9234-9234/com.cibn.tv:PluginP3 E/HookFactory:     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
11-25 17:17:33.840 9234-9234/com.cibn.tv:PluginP3 E/HookFactory:     at java.lang.Class.classForName(Native Method) 
11-25 17:17:33.840 9234-9234/com.cibn.tv:PluginP3 E/HookFactory:     at java.lang.Class.forName(Class.java:309) 
11-25 17:17:33.840 9234-9234/com.cibn.tv:PluginP3 E/HookFactory:     at java.lang.Class.forName(Class.java:273) 
11-25 17:17:33.840 9234-9234/com.cibn.tv:PluginP3 E/HookFactory:     at com.morgoo.helper.compat.IGraphicsStatsCompat.asInterface(IGraphicsStatsCompat.java:46) 
11-25 17:17:33.840 9234-9234/com.cibn.tv:PluginP3 E/HookFactory:     at com.morgoo.droidplugin.hook.binder.IGraphicsStatsBinderHook.getOldObj(IGraphicsStatsBinderHook.java:48) 
11-25 17:17:33.840 9234-9234/com.cibn.tv:PluginP3 E/HookFactory:     at com.morgoo.droidplugin.hook.binder.BinderHook.onInstall(BinderHook.java:96) 
11-25 17:17:33.840 9234-9234/com.cibn.tv:PluginP3 E/HookFactory:     at com.morgoo.droidplugin.hook.HookFactory.installHook(HookFactory.java:105) 
11-25 17:17:33.840 9234-9234/com.cibn.tv:PluginP3 E/HookFactory:     at com.morgoo.droidplugin.hook.HookFactory.installHook(HookFactory.java:126) 
11-25 17:17:33.840 9234-9234/com.cibn.tv:PluginP3 E/HookFactory:     at com.morgoo.droidplugin.core.PluginProcessManager.installHook(PluginProcessManager.java:296) 
11-25 17:17:33.840 9234-9234/com.cibn.tv:PluginP3 E/HookFactory:     at com.morgoo.droidplugin.PluginHelper.initPlugin(PluginHelper.java:76) 
11-25 17:17:33.840 9234-9234/com.cibn.tv:PluginP3 E/HookFactory:     at com.morgoo.droidplugin.PluginHelper.applicationOnCreate(PluginHelper.java:63) 
11-25 17:17:33.840 9234-9234/com.cibn.tv:PluginP3 E/HookFactory:     at com.morgoo.droidplugin.PluginApplication.onCreate(PluginApplication.java:45) 
11-25 17:17:33.840 9234-9234/com.cibn.tv:PluginP3 E/HookFactory:     at com.example.TestPlugin.App.onCreate(App.java:23) 
11-25 17:17:33.840 9234-9234/com.cibn.tv:PluginP3 E/HookFactory:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012) 
11-25 17:17:33.840 9234-9234/com.cibn.tv:PluginP3 E/HookFactory:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4553) 
11-25 17:17:33.840 9234-9234/com.cibn.tv:PluginP3 E/HookFactory:     at android.app.ActivityThread.access$1500(ActivityThread.java:151) 
11-25 17:17:33.840 9234-9234/com.cibn.tv:PluginP3 E/HookFactory:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364) 
11-25 17:17:33.840 9234-9234/com.cibn.tv:PluginP3 E/HookFactory:     at android.os.Handler.dispatchMessage(Handler.java:102) 
11-25 17:17:33.840 9234-9234/com.cibn.tv:PluginP3 E/HookFactory:     at android.os.Looper.loop(Looper.java:135) 
11-25 17:17:33.840 9234-9234/com.cibn.tv:PluginP3 E/HookFactory:     at android.app.ActivityThread.main(ActivityThread.java:5254) 
11-25 17:17:33.840 9234-9234/com.cibn.tv:PluginP3 E/HookFactory:     at java.lang.reflect.Method.invoke(Native Method) 
11-25 17:17:33.840 9234-9234/com.cibn.tv:PluginP3 E/HookFactory:     at java.lang.reflect.Method.invoke(Method.java:372) 
11-25 17:17:33.840 9234-9234/com.cibn.tv:PluginP3 E/HookFactory:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
11-25 17:17:33.840 9234-9234/com.cibn.tv:PluginP3 E/HookFactory:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
11-25 17:17:33.840 9234-9234/com.cibn.tv:PluginP3 E/HookFactory: 	Suppressed: java.lang.ClassNotFoundException: android.view.IGraphicsStats$Stub
11-25 17:17:33.840 9234-9234/com.cibn.tv:PluginP3 E/HookFactory:     at java.lang.Class.classForName(Native Method)
11-25 17:17:33.840 9234-9234/com.cibn.tv:PluginP3 E/HookFactory:     at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
11-25 17:17:33.840 9234-9234/com.cibn.tv:PluginP3 E/HookFactory:     at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
11-25 17:17:33.840 9234-9234/com.cibn.tv:PluginP3 E/HookFactory:     at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
11-25 17:17:33.840 9234-9234/com.cibn.tv:PluginP3 E/HookFactory:     		... 25 more
11-25 17:17:33.840 9234-9234/com.cibn.tv:PluginP3 E/HookFactory:  Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
11-25 17:17:33.884 9234-9234/com.cibn.tv:PluginP3 I/WebViewFactory: Loading com.android.webview version 39 (eng.bysong-arm) (code 399991)
11-25 17:17:33.898 9234-9234/com.cibn.tv:PluginP3 I/LibraryLoader: Time to load native libraries: 3 ms (timestamps 1019-1022)
11-25 17:17:33.898 9234-9234/com.cibn.tv:PluginP3 I/LibraryLoader: Expected native library version number "",actual native library version number ""
11-25 17:17:33.986 9234-9234/com.cibn.tv:PluginP3 I/IActivityManagerHook: Install ActivityManager Hook 2 old=android.app.ActivityManagerProxy@379a977a,new=android.app.ActivityManagerProxy@379a977a
11-25 17:17:33.990 9234-9234/com.cibn.tv:PluginP3 E/IActivityManagerHook: Install ActivityManager 3 Hook  old=android.app.ActivityManagerProxy@379a977a,new=android.app.ActivityManagerProxy@379a977a
11-25 17:17:33.995 9234-9234/com.cibn.tv:PluginP3 I/PluginCallbackHook: PluginCallbackHook has installed
11-25 17:17:33.999 9234-9234/com.cibn.tv:PluginP3 I/InstrumentationHook: Install Instrumentation Hook old=android.app.Instrumentation android.app.ActivityThread.mInstrumentation,new=com.morgoo.droidplugin.hook.handle.PluginInstrumentation@2955db2b
11-25 17:17:34.073 9234-9234/com.cibn.tv:PluginP3 I/PluginHelper: Init plugin in process cost 330 ms
11-25 17:17:34.076 9234-9234/com.cibn.tv:PluginP3 I/PluginCallback: handleMessage(100,LAUNCH_ACTIVITY) cost 0 ms
11-25 17:17:34.113 9234-9258/com.cibn.tv:PluginP3 D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
11-25 17:17:34.122 9234-9234/com.cibn.tv:PluginP3 D/Atlas: Validating map...
11-25 17:17:34.137 9234-9234/com.cibn.tv:PluginP3 I/PluginManager: onServiceConnected connected OK!
11-25 17:17:34.141 9234-9234/com.cibn.tv:PluginP3 I/PluginCallback: handleMessage(149,ENTER_ANIMATION_COMPLETE) cost 1 ms
11-25 17:17:34.151 9234-9259/com.cibn.tv:PluginP3 I/PluginCallbackHook: PluginCallbackHook has installed,skip
11-25 17:17:34.151 9234-9259/com.cibn.tv:PluginP3 I/InstrumentationHook: Instrumentation has installed,skip
11-25 17:17:34.151 9234-9259/com.cibn.tv:PluginP3 I/PluginManager: PluginManager ready!
11-25 17:17:34.165 9234-9258/com.cibn.tv:PluginP3 I/OpenGLRenderer: Initialized EGL, version 1.4
11-25 17:17:34.183 9234-9258/com.cibn.tv:PluginP3 D/OpenGLRenderer: Enabling debug mode 0
11-25 17:17:34.185 9234-9258/com.cibn.tv:PluginP3 D/mali_winsys: new_window_surface returns 0x3000

**Comment by luoqii** [comment]
problem is here: PluginProcessManager#initProcessList()

...  ...
            if (packageInfo.activities != null) {
                for (ActivityInfo info : packageInfo.activities) {
                    if (!sProcessList.contains(info.processName) && info.processName != null && info.name != null && info.name.indexOf(ActivityStub.class.getSimpleName()) < 0) {
                        sProcessList.add(info.processName);
                    }
                }
            }
... ...
