### ISSUE TITLE
Question:无法通过LocalActivityManager的startActivity启动plugin

### ISSUE THREAD

**Issue by hellohano** [Qihoo360/DroidPlugin#90]
报错:
11-26 10:59:31.014 15523-15523/com.example.TestPlugin E/dalvikvm: Dex cache directory isn't writable: /data/dalvik-cache
11-26 10:59:31.014 15523-15523/com.example.TestPlugin I/dalvikvm: Unable to open or create cache for /data/data/com.example.TestPlugin/Plugin/maf.nd.com.rulerdemo/apk/base-1.apk (/data/dalvik-cache/data@data@com.example.TestPlugin@Plugin@maf.nd.com.rulerdemo@apk@base-1.apk@classes.dex)
11-26 10:59:31.024 15523-15523/com.example.TestPlugin D/AndroidRuntime: Shutting down VM
11-26 10:59:31.024 15523-15523/com.example.TestPlugin W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x4187d270)
11-26 10:59:31.044 15523-15523/com.example.TestPlugin E/AndroidRuntime: FATAL EXCEPTION: main
11-26 10:59:31.044 15523-15523/com.example.TestPlugin E/AndroidRuntime: Process: com.example.TestPlugin, PID: 15523
11-26 10:59:31.044 15523-15523/com.example.TestPlugin E/AndroidRuntime: java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{maf.nd.com.rulerdemo/maf.nd.com.rulerdemo.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "maf.nd.com.rulerdemo.MainActivity" on path: DexPathList[[zip file "/data/data/com.example.TestPlugin/Plugin/maf.nd.com.rulerdemo/apk/base-1.apk"],nativeLibraryDirectories=[/data/data/com.example.TestPlugin/Plugin/maf.nd.com.rulerdemo/lib, /vendor/lib, /system/lib]]
11-26 10:59:31.044 15523-15523/com.example.TestPlugin E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2110)
11-26 10:59:31.044 15523-15523/com.example.TestPlugin E/AndroidRuntime:     at android.app.ActivityThread.startActivityNow(ActivityThread.java:2024)
11-26 10:59:31.044 15523-15523/com.example.TestPlugin E/AndroidRuntime:     at android.app.LocalActivityManager.moveToState(LocalActivityManager.java:135)
11-26 10:59:31.044 15523-15523/com.example.TestPlugin E/AndroidRuntime:     at android.app.LocalActivityManager.startActivity(LocalActivityManager.java:347)
11-26 10:59:31.044 15523-15523/com.example.TestPlugin E/AndroidRuntime:     at com.example.TestPlugin.InstalledFragment.onListItemClick(InstalledFragment.java:60)
11-26 10:59:31.044 15523-15523/com.example.TestPlugin E/AndroidRuntime:     at com.example.TestPlugin.InstalledFragment$3$1.onClick(InstalledFragment.java:173)
11-26 10:59:31.044 15523-15523/com.example.TestPlugin E/AndroidRuntime:     at android.view.View.performClick(View.java:4447)
11-26 10:59:31.044 15523-15523/com.example.TestPlugin E/AndroidRuntime:     at android.view.View$PerformClick.run(View.java:18457)
11-26 10:59:31.044 15523-15523/com.example.TestPlugin E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:733)
11-26 10:59:31.044 15523-15523/com.example.TestPlugin E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:95)
11-26 10:59:31.044 15523-15523/com.example.TestPlugin E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:136)
11-26 10:59:31.044 15523-15523/com.example.TestPlugin E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5001)
11-26 10:59:31.044 15523-15523/com.example.TestPlugin E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method)
11-26 10:59:31.044 15523-15523/com.example.TestPlugin E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:515)
11-26 10:59:31.044 15523-15523/com.example.TestPlugin E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:811)
11-26 10:59:31.044 15523-15523/com.example.TestPlugin E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:627)
11-26 10:59:31.044 15523-15523/com.example.TestPlugin E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)
11-26 10:59:31.044 15523-15523/com.example.TestPlugin E/AndroidRuntime:  Caused by: java.lang.ClassNotFoundException: Didn't find class "maf.nd.com.rulerdemo.MainActivity" on path: DexPathList[[zip file "/data/data/com.example.TestPlugin/Plugin/maf.nd.com.rulerdemo/apk/base-1.apk"],nativeLibraryDirectories=[/data/data/com.example.TestPlugin/Plugin/maf.nd.com.rulerdemo/lib, /vendor/lib, /system/lib]]
11-26 10:59:31.044 15523-15523/com.example.TestPlugin E/AndroidRuntime:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
11-26 10:59:31.044 15523-15523/com.example.TestPlugin E/AndroidRuntime:     at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
11-26 10:59:31.044 15523-15523/com.example.TestPlugin E/AndroidRuntime:     at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
11-26 10:59:31.044 15523-15523/com.example.TestPlugin E/AndroidRuntime:     at android.app.Instrumentation.newActivity(Instrumentation.java:1061)
11-26 10:59:31.044 15523-15523/com.example.TestPlugin E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2101)
11-26 10:59:31.044 15523-15523/com.example.TestPlugin E/AndroidRuntime:     at android.app.ActivityThread.startActivityNow(ActivityThread.java:2024) 
11-26 10:59:31.044 15523-15523/com.example.TestPlugin E/AndroidRuntime:     at android.app.LocalActivityManager.moveToState(LocalActivityManager.java:135) 
11-26 10:59:31.044 15523-15523/com.example.TestPlugin E/AndroidRuntime:     at android.app.LocalActivityManager.startActivity(LocalActivityManager.java:347) 
11-26 10:59:31.044 15523-15523/com.example.TestPlugin E/AndroidRuntime:     at com.example.TestPlugin.InstalledFragment.onListItemClick(InstalledFragment.java:60) 
11-26 10:59:31.044 15523-15523/com.example.TestPlugin E/AndroidRuntime:     at com.example.TestPlugin.InstalledFragment$3$1.onClick(InstalledFragment.java:173) 
11-26 10:59:31.044 15523-15523/com.example.TestPlugin E/AndroidRuntime:     at android.view.View.performClick(View.java:4447) 
11-26 10:59:31.044 15523-15523/com.example.TestPlugin E/AndroidRuntime:     at android.view.View$PerformClick.run(View.java:18457) 
11-26 10:59:31.044 15523-15523/com.example.TestPlugin E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:733) 
11-26 10:59:31.044 15523-15523/com.example.TestPlugin E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:95) 
11-26 10:59:31.044 15523-15523/com.example.TestPlugin E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:136) 
11-26 10:59:31.044 15523-15523/com.example.TestPlugin E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5001) 
11-26 10:59:31.044 15523-15523/com.example.TestPlugin E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method) 
11-26 10:59:31.044 15523-15523/com.example.TestPlugin E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:515) 
11-26 10:59:31.044 15523-15523/com.example.TestPlugin E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:811) 
11-26 10:59:31.044 15523-15523/com.example.TestPlugin E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:627) 
11-26 10:59:31.044 15523-15523/com.example.TestPlugin E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method) 
11-26 10:59:31.044 15523-15523/com.example.TestPlugin E/AndroidRuntime: 	Suppressed: java.io.IOException: unable to open DEX file
11-26 10:59:31.044 15523-15523/com.example.TestPlugin E/AndroidRuntime:     at dalvik.system.DexFile.openDexFileNative(Native Method)
11-26 10:59:31.044 15523-15523/com.example.TestPlugin E/AndroidRuntime:     at dalvik.system.DexFile.openDexFile(DexFile.java:296)
11-26 10:59:31.044 15523-15523/com.example.TestPlugin E/AndroidRuntime:     at dalvik.system.DexFile.<init>(DexFile.java:80)
11-26 10:59:31.044 15523-15523/com.example.TestPlugin E/AndroidRuntime:     at dalvik.system.DexFile.<init>(DexFile.java:59)
11-26 10:59:31.044 15523-15523/com.example.TestPlugin E/AndroidRuntime:     at dalvik.system.DexPathList.loadDexFile(DexPathList.java:263)
11-26 10:59:31.044 15523-15523/com.example.TestPlugin E/AndroidRuntime:     at dalvik.system.DexPathList.makeDexElements(DexPathList.java:230)
11-26 10:59:31.044 15523-15523/com.example.TestPlugin E/AndroidRuntime:     at dalvik.system.DexPathList.<init>(DexPathList.java:112)
11-26 10:59:31.044 15523-15523/com.example.TestPlugin E/AndroidRuntime:     at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
11-26 10:59:31.044 15523-15523/com.example.TestPlugin E/AndroidRuntime:     at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:65)
11-26 10:59:31.044 15523-15523/com.example.TestPlugin E/AndroidRuntime:     at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:57)
11-26 10:59:31.044 15523-15523/com.example.TestPlugin E/AndroidRuntime:     at android.app.LoadedApk.getClassLoader(LoadedApk.java:318)
11-26 10:59:31.044 15523-15523/com.example.TestPlugin E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2100)
11-26 10:59:31.044 15523-15523/com.example.TestPlugin E/AndroidRuntime:     		... 16 more

**Comment by cmzy** [comment]
这算一个新的功能。确实一直对LocalActivityManager支持不好。我想办法适配下。

**Comment by hellohano** [comment]
@cmzy 一个线索 在5.0上是可以正常工作的，我现在也在看5.0的相关代码
