### ISSUE TITLE
我用TestPlugin运行后安装apk，每次在 “已安装”程序列表中点击 打开，都会crash

### ISSUE THREAD

**Issue by DavidYes** [Qihoo360/DroidPlugin#99]
@Override
    public void onListItemClick(ListView l, View v, int position, long id) {
        ApkItem item = adapter.getItem(position);
        if (v.getId() == R.id.button2) {

            PackageManager pm = getActivity().getPackageManager();
            Intent intent = pm.getLaunchIntentForPackage(item.packageInfo.packageName);

具体就是每次这个inten得到的都是NULL,而目标apk是已经通过“待安装”界面安装过了。

12-09 14:38:55.965 1867-1867/com.example.TestPlugin E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      java.lang.NullPointerException
                                                                          at com.example.TestPlugin.InstalledFragment.onListItemClick(InstalledFragment.java:50)
                                                                          at com.example.TestPlugin.InstalledFragment$3$1.onClick(InstalledFragment.java:147)
                                                                          at android.view.View.performClick(View.java:4222)
                                                                          at android.view.View$PerformClick.run(View.java:17620)
                                                                          at android.os.Handler.handleCallback(Handler.java:800)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                          at android.os.Looper.loop(Looper.java:194)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5391)
                                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:525)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
                                                                          at dalvik.system.NativeStart.main(Native Method)

**Comment by Ewg777** [comment]
@DavidYes have you solved this?

**Comment by cmzy** [comment]
需要manifestmerger.enabled=true打开。
